import type { Word, WordCategory } from './words';

function tag(
  words: { target: string; ua: string; transcription: string }[],
  category: WordCategory,
): Word[] {
  return words.map((w) => ({ ...w, category }));
}

// ─── Дієслова ─────────────────────────────────────────────────────────────────

const VERBS_ES = tag(
  [
    { target: 'ser', ua: 'бути', transcription: '[ser]' },
    { target: 'estar', ua: 'бути (стан)', transcription: '[esˈtar]' },
    { target: 'tener', ua: 'мати', transcription: '[teˈner]' },
    { target: 'hacer', ua: 'робити', transcription: '[aˈθer]' },
    { target: 'poder', ua: 'могти', transcription: '[poˈðer]' },
    { target: 'decir', ua: 'говорити', transcription: '[deˈθir]' },
    { target: 'ir', ua: 'іти', transcription: '[ir]' },
    { target: 'ver', ua: 'бачити', transcription: '[ber]' },
    { target: 'dar', ua: 'давати', transcription: '[dar]' },
    { target: 'saber', ua: 'знати', transcription: '[saˈβer]' },
    { target: 'querer', ua: 'хотіти', transcription: '[keˈrer]' },
    { target: 'llegar', ua: 'прибувати', transcription: '[ʎeˈɣar]' },
    { target: 'pasar', ua: 'проходити', transcription: '[paˈsar]' },
    { target: 'deber', ua: 'повинен', transcription: '[deˈβer]' },
    { target: 'poner', ua: 'класти', transcription: '[poˈner]' },
    { target: 'parecer', ua: 'здаватися', transcription: '[pareˈθer]' },
    { target: 'quedar', ua: 'залишатися', transcription: '[keˈðar]' },
    { target: 'creer', ua: 'вірити', transcription: '[kreˈer]' },
    { target: 'hablar', ua: 'говорити', transcription: '[aˈβlar]' },
    { target: 'llevar', ua: 'нести', transcription: '[ʎeˈβar]' },
    { target: 'dejar', ua: 'залишати', transcription: '[deˈxar]' },
    { target: 'seguir', ua: 'слідувати', transcription: '[seˈɣir]' },
    { target: 'encontrar', ua: 'знаходити', transcription: '[enkõnˈtrar]' },
    { target: 'llamar', ua: 'телефонувати', transcription: '[ʎaˈmar]' },
    { target: 'venir', ua: 'приходити', transcription: '[beˈnir]' },
    { target: 'pensar', ua: 'думати', transcription: '[penˈsar]' },
    { target: 'salir', ua: 'виходити', transcription: '[saˈlir]' },
    { target: 'volver', ua: 'повертатися', transcription: '[bolˈber]' },
    { target: 'tomar', ua: 'брати', transcription: '[toˈmar]' },
    { target: 'conocer', ua: 'знати (особисто)', transcription: '[konoˈθer]' },
    { target: 'vivir', ua: 'жити', transcription: '[biˈβir]' },
    { target: 'sentir', ua: 'відчувати', transcription: '[senˈtir]' },
    { target: 'tratar', ua: 'намагатися', transcription: '[traˈtar]' },
    { target: 'mirar', ua: 'дивитися', transcription: '[miˈrar]' },
    { target: 'contar', ua: 'рахувати', transcription: '[konˈtar]' },
    { target: 'empezar', ua: 'починати', transcription: '[empeˈθar]' },
    { target: 'esperar', ua: 'чекати', transcription: '[espeˈrar]' },
    { target: 'buscar', ua: 'шукати', transcription: '[busˈkar]' },
    { target: 'existir', ua: 'існувати', transcription: '[eksisˈtir]' },
    { target: 'entrar', ua: 'входити', transcription: '[enˈtrar]' },
    { target: 'trabajar', ua: 'працювати', transcription: '[traβaˈxar]' },
    { target: 'escribir', ua: 'писати', transcription: '[esˈkɾiβir]' },
    { target: 'perder', ua: 'втрачати', transcription: '[perˈðer]' },
    { target: 'producir', ua: 'виробляти', transcription: '[proðuˈθir]' },
    { target: 'ocurrir', ua: 'відбуватися', transcription: '[okuˈrir]' },
    { target: 'entender', ua: 'розуміти', transcription: '[entenˈder]' },
    { target: 'pedir', ua: 'просити', transcription: '[peˈðir]' },
    { target: 'recibir', ua: 'отримувати', transcription: '[reθiˈβir]' },
    { target: 'recordar', ua: "пам'ятати", transcription: '[rekorˈðar]' },
    { target: 'morir', ua: 'вмирати', transcription: '[moˈrir]' },
  ],
  'verb',
);

// ─── Іменники ─────────────────────────────────────────────────────────────────

const NOUNS_ES = tag(
  [
    { target: 'tiempo', ua: 'час / погода', transcription: '[ˈtjempo]' },
    { target: 'año', ua: 'рік', transcription: '[ˈaɲo]' },
    { target: 'vida', ua: 'життя', transcription: '[ˈbiða]' },
    { target: 'mundo', ua: 'світ', transcription: '[ˈmundo]' },
    { target: 'casa', ua: 'будинок', transcription: '[ˈkasa]' },
    { target: 'hombre', ua: 'чоловік', transcription: '[ˈombre]' },
    { target: 'mujer', ua: 'жінка', transcription: '[muˈxer]' },
    { target: 'día', ua: 'день', transcription: '[ˈdia]' },
    { target: 'mano', ua: 'рука', transcription: '[ˈmano]' },
    { target: 'parte', ua: 'частина', transcription: '[ˈparte]' },
    { target: 'vez', ua: 'раз', transcription: '[beθ]' },
    { target: 'lugar', ua: 'місце', transcription: '[luˈɣar]' },
    { target: 'país', ua: 'країна', transcription: '[paˈis]' },
    { target: 'ciudad', ua: 'місто', transcription: '[θjuˈðað]' },
    { target: 'trabajo', ua: 'робота', transcription: '[traˈβaxo]' },
    { target: 'agua', ua: 'вода', transcription: '[ˈaɣwa]' },
    { target: 'noche', ua: 'ніч', transcription: '[ˈnotʃe]' },
    { target: 'forma', ua: 'форма', transcription: '[ˈforma]' },
    { target: 'nombre', ua: "ім'я", transcription: '[ˈnombre]' },
    { target: 'padre', ua: 'батько', transcription: '[ˈpaðre]' },
    { target: 'madre', ua: 'мати', transcription: '[ˈmaðre]' },
    { target: 'hijo', ua: 'син', transcription: '[ˈixo]' },
    { target: 'amigo', ua: 'друг', transcription: '[aˈmiɣo]' },
    { target: 'familia', ua: "сім'я", transcription: '[faˈmilja]' },
    { target: 'libro', ua: 'книга', transcription: '[ˈliβro]' },
    { target: 'coche', ua: 'автомобіль', transcription: '[ˈkotʃe]' },
    { target: 'puerta', ua: 'двері', transcription: '[ˈpwerta]' },
    { target: 'calle', ua: 'вулиця', transcription: '[ˈkaʎe]' },
    { target: 'comida', ua: 'їжа', transcription: '[koˈmiða]' },
    { target: 'dinero', ua: 'гроші', transcription: '[diˈnero]' },
    { target: 'pregunta', ua: 'питання', transcription: '[preˈɣunta]' },
    { target: 'respuesta', ua: 'відповідь', transcription: '[resˈpwesta]' },
    { target: 'idea', ua: 'ідея', transcription: '[iˈðea]' },
    { target: 'problema', ua: 'проблема', transcription: '[proˈβlema]' },
    { target: 'historia', ua: 'історія', transcription: '[isˈtorja]' },
    { target: 'gobierno', ua: 'уряд', transcription: '[ɡoˈβjerno]' },
    { target: 'empresa', ua: 'компанія', transcription: '[emˈpresa]' },
    { target: 'niño', ua: 'дитина', transcription: '[ˈniɲo]' },
    { target: 'escuela', ua: 'школа', transcription: '[esˈkwela]' },
    { target: 'pueblo', ua: 'народ / село', transcription: '[ˈpweβlo]' },
    { target: 'caso', ua: 'випадок', transcription: '[ˈkaso]' },
    { target: 'momento', ua: 'момент', transcription: '[moˈmento]' },
    { target: 'tipo', ua: 'тип', transcription: '[ˈtipo]' },
    { target: 'semana', ua: 'тиждень', transcription: '[seˈmana]' },
    { target: 'hora', ua: 'година', transcription: '[ˈora]' },
    { target: 'guerra', ua: 'війна', transcription: '[ˈɡera]' },
    { target: 'paz', ua: 'мир', transcription: '[paθ]' },
    { target: 'amor', ua: 'кохання', transcription: '[aˈmor]' },
    { target: 'corazón', ua: 'серце', transcription: '[koraˈθon]' },
    { target: 'palabra', ua: 'слово', transcription: '[paˈlaβra]' },
  ],
  'noun',
);

// ─── Прикметники ──────────────────────────────────────────────────────────────

const ADJECTIVES_ES = tag(
  [
    { target: 'bueno', ua: 'гарний', transcription: '[ˈbweno]' },
    { target: 'malo', ua: 'поганий', transcription: '[ˈmalo]' },
    { target: 'grande', ua: 'великий', transcription: '[ˈɡrande]' },
    { target: 'pequeño', ua: 'маленький', transcription: '[peˈkeɲo]' },
    { target: 'nuevo', ua: 'новий', transcription: '[ˈnweβo]' },
    { target: 'viejo', ua: 'старий', transcription: '[ˈbjexo]' },
    { target: 'mismo', ua: 'той самий', transcription: '[ˈmismo]' },
    { target: 'otro', ua: 'інший', transcription: '[ˈotro]' },
    { target: 'solo', ua: 'один / самотній', transcription: '[ˈsolo]' },
    { target: 'último', ua: 'останній', transcription: '[ˈultimo]' },
    { target: 'largo', ua: 'довгий', transcription: '[ˈlarɣo]' },
    { target: 'corto', ua: 'короткий', transcription: '[ˈkorto]' },
    { target: 'alto', ua: 'високий', transcription: '[ˈalto]' },
    { target: 'bajo', ua: 'низький', transcription: '[ˈbaxo]' },
    { target: 'fuerte', ua: 'сильний', transcription: '[ˈfwerte]' },
    { target: 'libre', ua: 'вільний', transcription: '[ˈliβre]' },
    { target: 'fácil', ua: 'легкий', transcription: '[ˈfaθil]' },
    { target: 'difícil', ua: 'складний', transcription: '[diˈfiθil]' },
    { target: 'posible', ua: 'можливий', transcription: '[poˈsiβle]' },
    { target: 'importante', ua: 'важливий', transcription: '[imporˈtante]' },
    { target: 'cierto', ua: 'певний', transcription: '[ˈθjerto]' },
    { target: 'verdadero', ua: 'справжній', transcription: '[berðaˈðero]' },
    { target: 'diferente', ua: 'різний', transcription: '[difeˈrente]' },
    { target: 'igual', ua: 'рівний', transcription: '[iˈɣwal]' },
    { target: 'feliz', ua: 'щасливий', transcription: '[feˈliθ]' },
    { target: 'triste', ua: 'сумний', transcription: '[ˈtriste]' },
    { target: 'rápido', ua: 'швидкий', transcription: '[ˈrapiðo]' },
    { target: 'lento', ua: 'повільний', transcription: '[ˈlento]' },
    { target: 'joven', ua: 'молодий', transcription: '[ˈxoβen]' },
    { target: 'bello', ua: 'красивий', transcription: '[ˈbeʎo]' },
  ],
  'adjective',
);

// ─── Прислівники ──────────────────────────────────────────────────────────────

const ADVERBS_ES = tag(
  [
    { target: 'también', ua: 'також', transcription: '[tamˈbjen]' },
    { target: 'ya', ua: 'вже', transcription: '[ʝa]' },
    { target: 'siempre', ua: 'завжди', transcription: '[ˈsjempre]' },
    { target: 'nunca', ua: 'ніколи', transcription: '[ˈnuŋka]' },
    { target: 'ahora', ua: 'зараз', transcription: '[aˈora]' },
    { target: 'aquí', ua: 'тут', transcription: '[aˈki]' },
    { target: 'allí', ua: 'там', transcription: '[aˈʎi]' },
    { target: 'mucho', ua: 'дуже / багато', transcription: '[ˈmutʃo]' },
    { target: 'poco', ua: 'мало', transcription: '[ˈpoko]' },
    { target: 'más', ua: 'більше', transcription: '[mas]' },
    { target: 'menos', ua: 'менше', transcription: '[ˈmenos]' },
    { target: 'muy', ua: 'дуже', transcription: '[mwi]' },
    { target: 'bien', ua: 'добре', transcription: '[bjen]' },
    { target: 'mal', ua: 'погано', transcription: '[mal]' },
    { target: 'así', ua: 'так / таким чином', transcription: '[aˈsi]' },
    { target: 'solo', ua: 'лише', transcription: '[ˈsolo]' },
    { target: 'todavía', ua: 'ще', transcription: '[toðaˈβia]' },
    { target: 'después', ua: 'потім', transcription: '[desˈpwes]' },
    { target: 'antes', ua: 'раніше', transcription: '[ˈantes]' },
    { target: 'cerca', ua: 'близько', transcription: '[ˈθerka]' },
  ],
  'adverb',
);

// ─── Exports ──────────────────────────────────────────────────────────────────

export const WORDS_ES: Word[] = [...VERBS_ES, ...NOUNS_ES, ...ADJECTIVES_ES, ...ADVERBS_ES];

export const WORDS_ES_BY_CATEGORY: Record<WordCategory, Word[]> = {
  verb: VERBS_ES,
  noun: NOUNS_ES,
  adjective: ADJECTIVES_ES,
  adverb: ADVERBS_ES,
};
