import type { Word, WordCategory } from './words';

function tag(
  words: { target: string; ua: string; transcription: string }[],
  category: WordCategory,
): Word[] {
  return words.map((w) => ({ ...w, category }));
}

// ─── Дієслова ─────────────────────────────────────────────────────────────────

const VERBS_DE = tag(
  [
    { target: 'sein', ua: 'бути', transcription: '[zaɪn]' },
    { target: 'haben', ua: 'мати', transcription: '[ˈhaːbən]' },
    { target: 'werden', ua: 'ставати', transcription: '[ˈveːrdən]' },
    { target: 'können', ua: 'могти', transcription: '[ˈkœnən]' },
    { target: 'müssen', ua: 'мусити', transcription: '[ˈmʏsən]' },
    { target: 'sagen', ua: 'говорити', transcription: '[ˈzaːɡən]' },
    { target: 'machen', ua: 'робити', transcription: '[ˈmaxən]' },
    { target: 'gehen', ua: 'іти', transcription: '[ˈɡeːən]' },
    { target: 'sehen', ua: 'бачити', transcription: '[ˈzeːən]' },
    { target: 'kommen', ua: 'приходити', transcription: '[ˈkɔmən]' },
    { target: 'wissen', ua: 'знати', transcription: '[ˈvɪsən]' },
    { target: 'wollen', ua: 'хотіти', transcription: '[ˈvɔlən]' },
    { target: 'geben', ua: 'давати', transcription: '[ˈɡeːbən]' },
    { target: 'nehmen', ua: 'брати', transcription: '[ˈneːmən]' },
    { target: 'denken', ua: 'думати', transcription: '[ˈdɛŋkən]' },
    { target: 'glauben', ua: 'вірити', transcription: '[ˈɡlaʊbən]' },
    { target: 'halten', ua: 'тримати', transcription: '[ˈhaltən]' },
    { target: 'finden', ua: 'знаходити', transcription: '[ˈfɪndən]' },
    { target: 'lassen', ua: 'залишати', transcription: '[ˈlasən]' },
    { target: 'stehen', ua: 'стояти', transcription: '[ˈʃteːən]' },
    { target: 'bleiben', ua: 'залишатися', transcription: '[ˈblaɪbən]' },
    { target: 'zeigen', ua: 'показувати', transcription: '[ˈtsaɪɡən]' },
    { target: 'führen', ua: 'вести', transcription: '[ˈfyːrən]' },
    { target: 'spielen', ua: 'грати', transcription: '[ˈʃpiːlən]' },
    { target: 'arbeiten', ua: 'працювати', transcription: '[ˈarbaɪtən]' },
    { target: 'leben', ua: 'жити', transcription: '[ˈleːbən]' },
    { target: 'sprechen', ua: 'говорити', transcription: '[ˈʃprɛçən]' },
    { target: 'bringen', ua: 'приносити', transcription: '[ˈbrɪŋən]' },
    { target: 'schreiben', ua: 'писати', transcription: '[ˈʃraɪbən]' },
    { target: 'laufen', ua: 'бігти', transcription: '[ˈlaʊfən]' },
    { target: 'hören', ua: 'чути', transcription: '[ˈhøːrən]' },
    { target: 'fragen', ua: 'запитувати', transcription: '[ˈfraːɡən]' },
    { target: 'suchen', ua: 'шукати', transcription: '[ˈzuːxən]' },
    { target: 'kaufen', ua: 'купувати', transcription: '[ˈkaʊfən]' },
    { target: 'helfen', ua: 'допомагати', transcription: '[ˈhɛlfən]' },
    { target: 'verstehen', ua: 'розуміти', transcription: '[fɛrˈʃteːən]' },
    { target: 'beginnen', ua: 'починати', transcription: '[bəˈɡɪnən]' },
    { target: 'lernen', ua: 'вчитися', transcription: '[ˈlɛrnən]' },
    { target: 'lesen', ua: 'читати', transcription: '[ˈleːzən]' },
    { target: 'treffen', ua: 'зустрічати', transcription: '[ˈtrɛfən]' },
    { target: 'warten', ua: 'чекати', transcription: '[ˈvartn̩]' },
    { target: 'reisen', ua: 'подорожувати', transcription: '[ˈraɪzən]' },
    { target: 'essen', ua: 'їсти', transcription: '[ˈɛsən]' },
    { target: 'trinken', ua: 'пити', transcription: '[ˈtrɪŋkən]' },
    { target: 'schlafen', ua: 'спати', transcription: '[ˈʃlaːfən]' },
    { target: 'fallen', ua: 'падати', transcription: '[ˈfalən]' },
    { target: 'verlieren', ua: 'втрачати', transcription: '[fɛrˈliːrən]' },
    { target: 'gewinnen', ua: 'вигравати', transcription: '[ɡəˈvɪnən]' },
    { target: 'öffnen', ua: 'відкривати', transcription: '[ˈœfnən]' },
    { target: 'schließen', ua: 'закривати', transcription: '[ˈʃliːsən]' },
  ],
  'verb',
);

// ─── Іменники ─────────────────────────────────────────────────────────────────

const NOUNS_DE = tag(
  [
    { target: 'Zeit', ua: 'час', transcription: '[tsaɪt]' },
    { target: 'Jahr', ua: 'рік', transcription: '[jaːr]' },
    { target: 'Leben', ua: 'життя', transcription: '[ˈleːbən]' },
    { target: 'Welt', ua: 'світ', transcription: '[vɛlt]' },
    { target: 'Haus', ua: 'будинок', transcription: '[haʊs]' },
    { target: 'Mann', ua: 'чоловік', transcription: '[man]' },
    { target: 'Frau', ua: 'жінка', transcription: '[fraʊ]' },
    { target: 'Tag', ua: 'день', transcription: '[taːk]' },
    { target: 'Hand', ua: 'рука', transcription: '[hant]' },
    { target: 'Land', ua: 'країна', transcription: '[lant]' },
    { target: 'Stadt', ua: 'місто', transcription: '[ʃtat]' },
    { target: 'Arbeit', ua: 'робота', transcription: '[ˈarbait]' },
    { target: 'Wasser', ua: 'вода', transcription: '[ˈvasər]' },
    { target: 'Nacht', ua: 'ніч', transcription: '[naxt]' },
    { target: 'Name', ua: "ім'я", transcription: '[ˈnaːmə]' },
    { target: 'Vater', ua: 'батько', transcription: '[ˈfaːtər]' },
    { target: 'Mutter', ua: 'мати', transcription: '[ˈmʊtər]' },
    { target: 'Kind', ua: 'дитина', transcription: '[kɪnt]' },
    { target: 'Freund', ua: 'друг', transcription: '[frɔʏnt]' },
    { target: 'Familie', ua: "сім'я", transcription: '[faˈmiːliə]' },
    { target: 'Buch', ua: 'книга', transcription: '[buːx]' },
    { target: 'Auto', ua: 'автомобіль', transcription: '[ˈaʊtoː]' },
    { target: 'Tür', ua: 'двері', transcription: '[tyːr]' },
    { target: 'Straße', ua: 'вулиця', transcription: '[ˈʃtraːsə]' },
    { target: 'Essen', ua: 'їжа', transcription: '[ˈɛsən]' },
    { target: 'Geld', ua: 'гроші', transcription: '[ɡɛlt]' },
    { target: 'Frage', ua: 'питання', transcription: '[ˈfraːɡə]' },
    { target: 'Antwort', ua: 'відповідь', transcription: '[ˈantvɔrt]' },
    { target: 'Idee', ua: 'ідея', transcription: '[iˈdeː]' },
    { target: 'Problem', ua: 'проблема', transcription: '[proˈbleːm]' },
    { target: 'Geschichte', ua: 'історія', transcription: '[ɡəˈʃɪçtə]' },
    { target: 'Regierung', ua: 'уряд', transcription: '[reˈɡiːrʊŋ]' },
    { target: 'Schule', ua: 'школа', transcription: '[ˈʃuːlə]' },
    { target: 'Moment', ua: 'момент', transcription: '[moˈmɛnt]' },
    { target: 'Woche', ua: 'тиждень', transcription: '[ˈvɔxə]' },
    { target: 'Stunde', ua: 'година', transcription: '[ˈʃtʊndə]' },
    { target: 'Krieg', ua: 'війна', transcription: '[kriːk]' },
    { target: 'Frieden', ua: 'мир', transcription: '[ˈfriːdən]' },
    { target: 'Liebe', ua: 'кохання', transcription: '[ˈliːbə]' },
    { target: 'Herz', ua: 'серце', transcription: '[hɛrts]' },
    { target: 'Wort', ua: 'слово', transcription: '[vɔrt]' },
    { target: 'Nummer', ua: 'номер', transcription: '[ˈnʊmər]' },
    { target: 'Weg', ua: 'шлях', transcription: '[veːk]' },
    { target: 'Platz', ua: 'місце', transcription: '[plats]' },
    { target: 'Baum', ua: 'дерево', transcription: '[baʊm]' },
    { target: 'Tier', ua: 'тварина', transcription: '[tiːr]' },
    { target: 'Himmel', ua: 'небо', transcription: '[ˈhɪməl]' },
    { target: 'Musik', ua: 'музика', transcription: '[muˈziːk]' },
    { target: 'Sport', ua: 'спорт', transcription: '[ʃpɔrt]' },
    { target: 'Gesundheit', ua: "здоров'я", transcription: '[ɡəˈzʊnthaɪt]' },
  ],
  'noun',
);

// ─── Прикметники ──────────────────────────────────────────────────────────────

const ADJECTIVES_DE = tag(
  [
    { target: 'gut', ua: 'гарний', transcription: '[ɡuːt]' },
    { target: 'schlecht', ua: 'поганий', transcription: '[ʃlɛçt]' },
    { target: 'groß', ua: 'великий', transcription: '[ɡroːs]' },
    { target: 'klein', ua: 'маленький', transcription: '[klaɪn]' },
    { target: 'neu', ua: 'новий', transcription: '[nɔɪ]' },
    { target: 'alt', ua: 'старий', transcription: '[alt]' },
    { target: 'lang', ua: 'довгий', transcription: '[laŋ]' },
    { target: 'kurz', ua: 'короткий', transcription: '[kʊrts]' },
    { target: 'hoch', ua: 'високий', transcription: '[hoːx]' },
    { target: 'niedrig', ua: 'низький', transcription: '[ˈniːdrɪç]' },
    { target: 'stark', ua: 'сильний', transcription: '[ʃtark]' },
    { target: 'frei', ua: 'вільний', transcription: '[fraɪ]' },
    { target: 'leicht', ua: 'легкий', transcription: '[laɪçt]' },
    { target: 'schwer', ua: 'важкий / складний', transcription: '[ʃveːr]' },
    { target: 'möglich', ua: 'можливий', transcription: '[ˈmøːklɪç]' },
    { target: 'wichtig', ua: 'важливий', transcription: '[ˈvɪçtɪç]' },
    { target: 'sicher', ua: 'безпечний', transcription: '[ˈzɪçər]' },
    { target: 'wahr', ua: 'правдивий', transcription: '[vaːr]' },
    { target: 'anders', ua: 'інший', transcription: '[ˈandərs]' },
    { target: 'gleich', ua: 'рівний', transcription: '[ɡlaɪç]' },
    { target: 'glücklich', ua: 'щасливий', transcription: '[ˈɡlʏklɪç]' },
    { target: 'traurig', ua: 'сумний', transcription: '[ˈtraʊrɪç]' },
    { target: 'schnell', ua: 'швидкий', transcription: '[ʃnɛl]' },
    { target: 'langsam', ua: 'повільний', transcription: '[ˈlaŋzaːm]' },
    { target: 'jung', ua: 'молодий', transcription: '[jʊŋ]' },
    { target: 'schön', ua: 'красивий', transcription: '[ʃøːn]' },
    { target: 'kalt', ua: 'холодний', transcription: '[kalt]' },
    { target: 'warm', ua: 'теплий', transcription: '[varm]' },
    { target: 'voll', ua: 'повний', transcription: '[fɔl]' },
    { target: 'leer', ua: 'порожній', transcription: '[leːr]' },
  ],
  'adjective',
);

// ─── Прислівники ──────────────────────────────────────────────────────────────

const ADVERBS_DE = tag(
  [
    { target: 'auch', ua: 'також', transcription: '[aʊx]' },
    { target: 'schon', ua: 'вже', transcription: '[ʃoːn]' },
    { target: 'immer', ua: 'завжди', transcription: '[ˈɪmər]' },
    { target: 'nie', ua: 'ніколи', transcription: '[niː]' },
    { target: 'jetzt', ua: 'зараз', transcription: '[jɛtst]' },
    { target: 'hier', ua: 'тут', transcription: '[hiːr]' },
    { target: 'dort', ua: 'там', transcription: '[dɔrt]' },
    { target: 'viel', ua: 'багато', transcription: '[fiːl]' },
    { target: 'wenig', ua: 'мало', transcription: '[ˈveːnɪç]' },
    { target: 'mehr', ua: 'більше', transcription: '[meːr]' },
    { target: 'weniger', ua: 'менше', transcription: '[ˈveːnɪɡər]' },
    { target: 'sehr', ua: 'дуже', transcription: '[zeːr]' },
    { target: 'gut', ua: 'добре', transcription: '[ɡuːt]' },
    { target: 'schlecht', ua: 'погано', transcription: '[ʃlɛçt]' },
    { target: 'so', ua: 'так / таким чином', transcription: '[zoː]' },
    { target: 'nur', ua: 'лише', transcription: '[nuːr]' },
    { target: 'noch', ua: 'ще', transcription: '[nɔx]' },
    { target: 'dann', ua: 'потім', transcription: '[dan]' },
    { target: 'vorher', ua: 'раніше', transcription: '[ˈfoːrheːr]' },
    { target: 'nah', ua: 'близько', transcription: '[naː]' },
  ],
  'adverb',
);

// ─── Exports ──────────────────────────────────────────────────────────────────

export const WORDS_DE: Word[] = [...VERBS_DE, ...NOUNS_DE, ...ADJECTIVES_DE, ...ADVERBS_DE];

export const WORDS_DE_BY_CATEGORY: Record<WordCategory, Word[]> = {
  verb: VERBS_DE,
  noun: NOUNS_DE,
  adjective: ADJECTIVES_DE,
  adverb: ADVERBS_DE,
};
