import type { Word, WordCategory } from './words';

// Ukrainian word list derived from English words.ts
// target = Ukrainian word being learned
// ua     = English translation (used as "answer" field in quiz)
// transcription = empty (no Ukrainian IPA data available)

function tag(
  words: { target: string; ua: string; transcription: string }[],
  category: WordCategory,
): Word[] {
  return words.map((w) => ({ ...w, category }));
}

// ─── Дієслова ─────────────────────────────────────────────────────────────────

const VERBS_UA = tag(
  [
    { target: 'бути', ua: 'be', transcription: '' },
    { target: 'мати', ua: 'have', transcription: '' },
    { target: 'робити', ua: 'do', transcription: '' },
    { target: 'казати', ua: 'say', transcription: '' },
    { target: 'отримувати', ua: 'get', transcription: '' },
    { target: 'іти', ua: 'go', transcription: '' },
    { target: 'знати', ua: 'know', transcription: '' },
    { target: 'брати', ua: 'take', transcription: '' },
    { target: 'бачити', ua: 'see', transcription: '' },
    { target: 'приходити', ua: 'come', transcription: '' },
    { target: 'думати', ua: 'think', transcription: '' },
    { target: 'дивитися', ua: 'look', transcription: '' },
    { target: 'хотіти', ua: 'want', transcription: '' },
    { target: 'давати', ua: 'give', transcription: '' },
    { target: 'використовувати', ua: 'use', transcription: '' },
    { target: 'знаходити', ua: 'find', transcription: '' },
    { target: 'розповідати', ua: 'tell', transcription: '' },
    { target: 'запитувати', ua: 'ask', transcription: '' },
    { target: 'здаватися', ua: 'seem', transcription: '' },
    { target: 'відчувати', ua: 'feel', transcription: '' },
    { target: 'намагатися', ua: 'try', transcription: '' },
    { target: 'залишати', ua: 'leave', transcription: '' },
    { target: 'телефонувати', ua: 'call', transcription: '' },
    { target: 'тримати', ua: 'keep', transcription: '' },
    { target: 'дозволяти', ua: 'let', transcription: '' },
    { target: 'починати', ua: 'begin', transcription: '' },
    { target: 'показувати', ua: 'show', transcription: '' },
    { target: 'чути', ua: 'hear', transcription: '' },
    { target: 'грати', ua: 'play', transcription: '' },
    { target: 'бігти', ua: 'run', transcription: '' },
    { target: 'рухатися', ua: 'move', transcription: '' },
    { target: 'жити', ua: 'live', transcription: '' },
    { target: 'вірити', ua: 'believe', transcription: '' },
    { target: 'приносити', ua: 'bring', transcription: '' },
    { target: 'відбуватися', ua: 'happen', transcription: '' },
    { target: 'писати', ua: 'write', transcription: '' },
    { target: 'забезпечувати', ua: 'provide', transcription: '' },
    { target: 'сидіти', ua: 'sit', transcription: '' },
    { target: 'стояти', ua: 'stand', transcription: '' },
    { target: 'втрачати', ua: 'lose', transcription: '' },
    { target: 'платити', ua: 'pay', transcription: '' },
    { target: 'зустрічати', ua: 'meet', transcription: '' },
    { target: 'включати', ua: 'include', transcription: '' },
    { target: 'продовжувати', ua: 'continue', transcription: '' },
    { target: 'встановлювати', ua: 'set', transcription: '' },
    { target: 'вчитися', ua: 'learn', transcription: '' },
    { target: 'вести', ua: 'lead', transcription: '' },
    { target: 'розуміти', ua: 'understand', transcription: '' },
    { target: 'слідувати', ua: 'follow', transcription: '' },
    { target: 'зупинятися', ua: 'stop', transcription: '' },
    { target: 'створювати', ua: 'create', transcription: '' },
    { target: 'розмовляти', ua: 'speak', transcription: '' },
    { target: 'читати', ua: 'read', transcription: '' },
    { target: 'витрачати', ua: 'spend', transcription: '' },
    { target: 'рости', ua: 'grow', transcription: '' },
    { target: 'відкривати', ua: 'open', transcription: '' },
    { target: 'ходити', ua: 'walk', transcription: '' },
    { target: 'перемагати', ua: 'win', transcription: '' },
    { target: 'пропонувати', ua: 'offer', transcription: '' },
    { target: "пам'ятати", ua: 'remember', transcription: '' },
    { target: 'вважати', ua: 'consider', transcription: '' },
    { target: "з'являтися", ua: 'appear', transcription: '' },
    { target: 'купувати', ua: 'buy', transcription: '' },
    { target: 'чекати', ua: 'wait', transcription: '' },
    { target: 'обслуговувати', ua: 'serve', transcription: '' },
    { target: 'відправляти', ua: 'send', transcription: '' },
    { target: 'очікувати', ua: 'expect', transcription: '' },
    { target: 'будувати', ua: 'build', transcription: '' },
    { target: 'залишатися', ua: 'stay', transcription: '' },
    { target: 'падати', ua: 'fall', transcription: '' },
    { target: 'різати', ua: 'cut', transcription: '' },
    { target: 'досягати', ua: 'reach', transcription: '' },
    { target: 'піднімати', ua: 'raise', transcription: '' },
    { target: 'проходити', ua: 'pass', transcription: '' },
    { target: 'продавати', ua: 'sell', transcription: '' },
    { target: 'вимагати', ua: 'require', transcription: '' },
    { target: 'повідомляти', ua: 'report', transcription: '' },
    { target: 'вирішувати', ua: 'decide', transcription: '' },
    { target: 'тягнути', ua: 'pull', transcription: '' },
    { target: 'розбивати', ua: 'break', transcription: '' },
    { target: 'нести', ua: 'carry', transcription: '' },
    { target: 'кидати', ua: 'throw', transcription: '' },
    { target: 'ловити', ua: 'catch', transcription: '' },
    { target: 'штовхати', ua: 'push', transcription: '' },
    { target: 'повертати', ua: 'turn', transcription: '' },
    { target: 'повертатися', ua: 'return', transcription: '' },
    { target: 'пояснювати', ua: 'explain', transcription: '' },
    { target: 'вибирати', ua: 'choose', transcription: '' },
    { target: 'закривати', ua: 'close', transcription: '' },
    { target: 'водити', ua: 'drive', transcription: '' },
    { target: 'їсти', ua: 'eat', transcription: '' },
    { target: 'пити', ua: 'drink', transcription: '' },
    { target: 'спати', ua: 'sleep', transcription: '' },
    { target: 'допомагати', ua: 'help', transcription: '' },
    { target: 'додавати', ua: 'add', transcription: '' },
    { target: 'відповідати', ua: 'answer', transcription: '' },
    { target: 'перевіряти', ua: 'check', transcription: '' },
    { target: 'покривати', ua: 'cover', transcription: '' },
    { target: 'входити', ua: 'enter', transcription: '' },
    { target: 'боротися', ua: 'fight', transcription: '' },
    { target: 'літати', ua: 'fly', transcription: '' },
    { target: 'забувати', ua: 'forget', transcription: '' },
    { target: 'вдаряти', ua: 'hit', transcription: '' },
    { target: 'стрибати', ua: 'jump', transcription: '' },
    { target: 'сміятися', ua: 'laugh', transcription: '' },
    { target: 'брехати', ua: 'lie', transcription: '' },
    { target: 'підіймати', ua: 'lift', transcription: '' },
    { target: 'слухати', ua: 'listen', transcription: '' },
    { target: 'скучати', ua: 'miss', transcription: '' },
    { target: 'помічати', ua: 'notice', transcription: '' },
    { target: 'воліти', ua: 'prefer', transcription: '' },
    { target: 'готувати', ua: 'prepare', transcription: '' },
    { target: 'запобігати', ua: 'prevent', transcription: '' },
    { target: 'захищати', ua: 'protect', transcription: '' },
    { target: 'доводити', ua: 'prove', transcription: '' },
    { target: 'зменшувати', ua: 'reduce', transcription: '' },
    { target: 'замінювати', ua: 'replace', transcription: '' },
    { target: 'рятувати', ua: 'save', transcription: '' },
    { target: 'ділитися', ua: 'share', transcription: '' },
    { target: 'посміхатися', ua: 'smile', transcription: '' },
    { target: "розв'язувати", ua: 'solve', transcription: '' },
    { target: 'підтримувати', ua: 'support', transcription: '' },
    { target: 'дивувати', ua: 'surprise', transcription: '' },
    { target: 'виживати', ua: 'survive', transcription: '' },
    { target: 'навчати', ua: 'teach', transcription: '' },
    { target: 'торкатися', ua: 'touch', transcription: '' },
    { target: 'подорожувати', ua: 'travel', transcription: '' },
    { target: 'довіряти', ua: 'trust', transcription: '' },
    { target: 'відвідувати', ua: 'visit', transcription: '' },
    { target: 'прокидатися', ua: 'wake', transcription: '' },
    { target: 'носити', ua: 'wear', transcription: '' },
    { target: 'бажати', ua: 'wish', transcription: '' },
    { target: 'працювати', ua: 'work', transcription: '' },
    { target: 'турбуватися', ua: 'worry', transcription: '' },
    { target: 'приймати', ua: 'accept', transcription: '' },
    { target: 'здобувати', ua: 'achieve', transcription: '' },
    { target: 'уникати', ua: 'avoid', transcription: '' },
    { target: 'святкувати', ua: 'celebrate', transcription: '' },
    { target: 'збирати', ua: 'collect', transcription: '' },
    { target: 'порівнювати', ua: 'compare', transcription: '' },
    { target: "з'єднувати", ua: 'connect', transcription: '' },
    { target: 'переконувати', ua: 'convince', transcription: '' },
    { target: 'рахувати', ua: 'count', transcription: '' },
    { target: 'дивитися (відео)', ua: 'watch', transcription: '' },
  ],
  'verb',
);

// ─── Іменники ─────────────────────────────────────────────────────────────────

const NOUNS_UA = tag(
  [
    { target: 'час', ua: 'time', transcription: '' },
    { target: 'людина', ua: 'person', transcription: '' },
    { target: 'рік', ua: 'year', transcription: '' },
    { target: 'спосіб', ua: 'way', transcription: '' },
    { target: 'день', ua: 'day', transcription: '' },
    { target: 'річ', ua: 'thing', transcription: '' },
    { target: 'чоловік', ua: 'man', transcription: '' },
    { target: 'світ', ua: 'world', transcription: '' },
    { target: 'життя', ua: 'life', transcription: '' },
    { target: 'рука', ua: 'hand', transcription: '' },
    { target: 'частина', ua: 'part', transcription: '' },
    { target: 'місце', ua: 'place', transcription: '' },
    { target: 'тиждень', ua: 'week', transcription: '' },
    { target: 'компанія', ua: 'company', transcription: '' },
    { target: 'група', ua: 'group', transcription: '' },
    { target: 'проблема', ua: 'problem', transcription: '' },
    { target: 'факт', ua: 'fact', transcription: '' },
    { target: 'гроші', ua: 'money', transcription: '' },
    { target: 'число', ua: 'number', transcription: '' },
    { target: 'ніч', ua: 'night', transcription: '' },
    { target: 'місто', ua: 'city', transcription: '' },
    { target: "ім'я", ua: 'name', transcription: '' },
    { target: 'дім', ua: 'home', transcription: '' },
    { target: 'вода', ua: 'water', transcription: '' },
    { target: 'кімната', ua: 'room', transcription: '' },
    { target: 'мати', ua: 'mother', transcription: '' },
    { target: 'ділянка', ua: 'area', transcription: '' },
    { target: "сім'я", ua: 'family', transcription: '' },
    { target: 'тіло', ua: 'body', transcription: '' },
    { target: 'око', ua: 'eye', transcription: '' },
    { target: 'їжа', ua: 'food', transcription: '' },
    { target: 'дитина', ua: 'child', transcription: '' },
    { target: 'двері', ua: 'door', transcription: '' },
    { target: 'країна', ua: 'country', transcription: '' },
    { target: 'питання', ua: 'question', transcription: '' },
    { target: 'голова', ua: 'head', transcription: '' },
    { target: 'серце', ua: 'heart', transcription: '' },
    { target: 'ідея', ua: 'idea', transcription: '' },
    { target: 'школа', ua: 'school', transcription: '' },
    { target: 'оповідання', ua: 'story', transcription: '' },
    { target: 'книга', ua: 'book', transcription: '' },
    { target: 'вулиця', ua: 'street', transcription: '' },
    { target: 'мить', ua: 'moment', transcription: '' },
    { target: 'обличчя', ua: 'face', transcription: '' },
    { target: 'друг', ua: 'friend', transcription: '' },
    { target: 'ранок', ua: 'morning', transcription: '' },
    { target: 'дівчина', ua: 'girl', transcription: '' },
    { target: 'хлопець', ua: 'boy', transcription: '' },
    { target: 'сила', ua: 'power', transcription: '' },
    { target: 'слово', ua: 'word', transcription: '' },
    { target: 'дорога', ua: 'road', transcription: '' },
    { target: 'місяць', ua: 'month', transcription: '' },
    { target: 'лінія', ua: 'line', transcription: '' },
    { target: 'уряд', ua: 'government', transcription: '' },
    { target: 'автомобіль', ua: 'car', transcription: '' },
    { target: 'містечко', ua: 'town', transcription: '' },
    { target: 'мова', ua: 'language', transcription: '' },
    { target: 'рівень', ua: 'level', transcription: '' },
    { target: 'повітря', ua: 'air', transcription: '' },
    { target: 'година', ua: 'hour', transcription: '' },
    { target: 'гра', ua: 'game', transcription: '' },
    { target: 'вогонь', ua: 'fire', transcription: '' },
    { target: 'земля', ua: 'land', transcription: '' },
    { target: 'вік', ua: 'age', transcription: '' },
    { target: 'голос', ua: 'voice', transcription: '' },
    { target: 'колір', ua: 'color', transcription: '' },
    { target: 'звук', ua: 'sound', transcription: '' },
    { target: 'новини', ua: 'news', transcription: '' },
    { target: 'світло', ua: 'light', transcription: '' },
    { target: 'тип', ua: 'type', transcription: '' },
    { target: 'клас', ua: 'class', transcription: '' },
    { target: 'період', ua: 'period', transcription: '' },
    { target: 'будівля', ua: 'building', transcription: '' },
    { target: 'поле', ua: 'field', transcription: '' },
    { target: 'бізнес', ua: 'business', transcription: '' },
    { target: 'картина', ua: 'picture', transcription: '' },
    { target: 'простір', ua: 'space', transcription: '' },
    { target: 'вид', ua: 'view', transcription: '' },
    { target: 'будинок', ua: 'house', transcription: '' },
    { target: 'команда', ua: 'team', transcription: '' },
    { target: 'послуга', ua: 'service', transcription: '' },
    { target: 'ціна', ua: 'price', transcription: '' },
    { target: 'волосся', ua: 'hair', transcription: '' },
    { target: 'відпочинок', ua: 'rest', transcription: '' },
    { target: 'крок', ua: 'step', transcription: '' },
    { target: 'закон', ua: 'law', transcription: '' },
    { target: 'століття', ua: 'century', transcription: '' },
    { target: 'держава', ua: 'state', transcription: '' },
    { target: 'війна', ua: 'war', transcription: '' },
    { target: 'вечірка', ua: 'party', transcription: '' },
    { target: 'суспільство', ua: 'society', transcription: '' },
    { target: 'музика', ua: 'music', transcription: '' },
    { target: 'офіс', ua: 'office', transcription: '' },
    { target: 'позиція', ua: 'position', transcription: '' },
    { target: 'роль', ua: 'role', transcription: '' },
    { target: 'президент', ua: 'president', transcription: '' },
    { target: 'рішення', ua: 'decision', transcription: '' },
    { target: 'причина', ua: 'reason', transcription: '' },
    { target: 'природа', ua: 'nature', transcription: '' },
    { target: 'система', ua: 'system', transcription: '' },
    { target: 'кохання', ua: 'love', transcription: '' },
    { target: 'план', ua: 'plan', transcription: '' },
    { target: 'мистецтво', ua: 'art', transcription: '' },
    { target: 'розвиток', ua: 'development', transcription: '' },
    { target: 'безпека', ua: 'security', transcription: '' },
    { target: 'майбутнє', ua: 'future', transcription: '' },
    { target: 'шанс', ua: 'chance', transcription: '' },
    { target: 'зміна', ua: 'change', transcription: '' },
    { target: 'спільнота', ua: 'community', transcription: '' },
    { target: 'центр', ua: 'center', transcription: '' },
    { target: 'результат', ua: 'result', transcription: '' },
    { target: 'модель', ua: 'model', transcription: '' },
    { target: 'економіка', ua: 'economy', transcription: '' },
    { target: 'енергія', ua: 'energy', transcription: '' },
    { target: 'досвід', ua: 'experience', transcription: '' },
    { target: 'освіта', ua: 'education', transcription: '' },
    { target: 'успіх', ua: 'success', transcription: '' },
    { target: 'цінність', ua: 'value', transcription: '' },
    { target: 'історія', ua: 'history', transcription: '' },
    { target: 'папір', ua: 'paper', transcription: '' },
    { target: 'дослідження', ua: 'research', transcription: '' },
    { target: 'здібність', ua: 'ability', transcription: '' },
    { target: 'стосунки', ua: 'relationship', transcription: '' },
    { target: 'вечір', ua: 'evening', transcription: '' },
    { target: 'увага', ua: 'attention', transcription: '' },
    { target: 'культура', ua: 'culture', transcription: '' },
    { target: 'правда', ua: 'truth', transcription: '' },
    { target: 'лідер', ua: 'leader', transcription: '' },
    { target: 'студент', ua: 'student', transcription: '' },
    { target: 'вчитель', ua: 'teacher', transcription: '' },
    { target: 'батьки', ua: 'parent', transcription: '' },
    { target: 'вікно', ua: 'window', transcription: '' },
    { target: 'стіл', ua: 'table', transcription: '' },
    { target: 'стілець', ua: 'chair', transcription: '' },
    { target: 'ліжко', ua: 'bed', transcription: '' },
    { target: 'сонце', ua: 'sun', transcription: '' },
    { target: 'дерево', ua: 'tree', transcription: '' },
    { target: 'річка', ua: 'river', transcription: '' },
    { target: 'море', ua: 'sea', transcription: '' },
    { target: 'гора', ua: 'mountain', transcription: '' },
    { target: 'небо', ua: 'sky', transcription: '' },
    { target: 'тварина', ua: 'animal', transcription: '' },
    { target: 'собака', ua: 'dog', transcription: '' },
    { target: 'кіт', ua: 'cat', transcription: '' },
    { target: 'птах', ua: 'bird', transcription: '' },
    { target: 'риба', ua: 'fish', transcription: '' },
    { target: 'квітка', ua: 'flower', transcription: '' },
    { target: 'сад', ua: 'garden', transcription: '' },
    { target: 'магазин', ua: 'store', transcription: '' },
    { target: 'лікарня', ua: 'hospital', transcription: '' },
    { target: 'лист', ua: 'letter', transcription: '' },
    { target: 'лікар', ua: 'doctor', transcription: '' },
    { target: 'поліція', ua: 'police', transcription: '' },
    { target: 'солдат', ua: 'soldier', transcription: '' },
    { target: 'король', ua: 'king', transcription: '' },
    { target: 'королева', ua: 'queen', transcription: '' },
    { target: 'немовля', ua: 'baby', transcription: '' },
    { target: 'брат', ua: 'brother', transcription: '' },
    { target: 'сестра', ua: 'sister', transcription: '' },
    { target: 'батько', ua: 'father', transcription: '' },
    { target: 'дружина', ua: 'wife', transcription: '' },
    { target: 'син', ua: 'son', transcription: '' },
    { target: 'дочка', ua: 'daughter', transcription: '' },
    { target: 'сусід', ua: 'neighbor', transcription: '' },
    { target: 'ворог', ua: 'enemy', transcription: '' },
    { target: 'церква', ua: 'church', transcription: '' },
    { target: 'бібліотека', ua: 'library', transcription: '' },
    { target: 'аеропорт', ua: 'airport', transcription: '' },
    { target: 'станція', ua: 'station', transcription: '' },
    { target: 'армія', ua: 'army', transcription: '' },
    { target: 'ліс', ua: 'forest', transcription: '' },
    { target: 'озеро', ua: 'lake', transcription: '' },
    { target: 'пляж', ua: 'beach', transcription: '' },
    { target: 'дощ', ua: 'rain', transcription: '' },
    { target: 'сніг', ua: 'snow', transcription: '' },
    { target: 'зірка', ua: 'star', transcription: '' },
  ],
  'noun',
);

// ─── Прикметники ──────────────────────────────────────────────────────────────

const ADJECTIVES_UA = tag(
  [
    { target: 'добрий', ua: 'good', transcription: '' },
    { target: 'новий', ua: 'new', transcription: '' },
    { target: 'перший', ua: 'first', transcription: '' },
    { target: 'останній', ua: 'last', transcription: '' },
    { target: 'довгий', ua: 'long', transcription: '' },
    { target: 'чудовий', ua: 'great', transcription: '' },
    { target: 'маленький', ua: 'little', transcription: '' },
    { target: 'власний', ua: 'own', transcription: '' },
    { target: 'інший', ua: 'other', transcription: '' },
    { target: 'старий', ua: 'old', transcription: '' },
    { target: 'правильний', ua: 'right', transcription: '' },
    { target: 'великий', ua: 'big', transcription: '' },
    { target: 'високий', ua: 'high', transcription: '' },
    { target: 'різний', ua: 'different', transcription: '' },
    { target: 'малий', ua: 'small', transcription: '' },
    { target: 'наступний', ua: 'next', transcription: '' },
    { target: 'ранній', ua: 'early', transcription: '' },
    { target: 'молодий', ua: 'young', transcription: '' },
    { target: 'важливий', ua: 'important', transcription: '' },
    { target: 'публічний', ua: 'public', transcription: '' },
    { target: 'поганий', ua: 'bad', transcription: '' },
    { target: 'однаковий', ua: 'same', transcription: '' },
    { target: 'здатний', ua: 'able', transcription: '' },
    { target: 'справжній', ua: 'real', transcription: '' },
    { target: 'найкращий', ua: 'best', transcription: '' },
    { target: 'вільний', ua: 'free', transcription: '' },
    { target: 'впевнений', ua: 'sure', transcription: '' },
    { target: 'кращий', ua: 'better', transcription: '' },
    { target: 'правдивий', ua: 'true', transcription: '' },
    { target: 'складний', ua: 'hard', transcription: '' },
    { target: 'низький', ua: 'low', transcription: '' },
    { target: 'короткий', ua: 'short', transcription: '' },
    { target: 'чіткий', ua: 'clear', transcription: '' },
    { target: 'нещодавній', ua: 'recent', transcription: '' },
    { target: 'лівий', ua: 'left', transcription: '' },
    { target: 'політичний', ua: 'political', transcription: '' },
    { target: 'соціальний', ua: 'social', transcription: '' },
    { target: 'економічний', ua: 'economic', transcription: '' },
    { target: 'місцевий', ua: 'local', transcription: '' },
    { target: 'національний', ua: 'national', transcription: '' },
    { target: 'повний', ua: 'full', transcription: '' },
    { target: 'гарячий', ua: 'hot', transcription: '' },
    { target: 'темний', ua: 'dark', transcription: '' },
    { target: 'сильний', ua: 'strong', transcription: '' },
    { target: 'глибокий', ua: 'deep', transcription: '' },
    { target: 'важкий', ua: 'heavy', transcription: '' },
    { target: 'холодний', ua: 'cold', transcription: '' },
    { target: 'теплий', ua: 'warm', transcription: '' },
    { target: 'чистий', ua: 'clean', transcription: '' },
    { target: 'сухий', ua: 'dry', transcription: '' },
    { target: 'неправильний', ua: 'wrong', transcription: '' },
    { target: 'щасливий', ua: 'happy', transcription: '' },
    { target: 'пізній', ua: 'late', transcription: '' },
    { target: 'готовий', ua: 'ready', transcription: '' },
    { target: 'простий', ua: 'simple', transcription: '' },
    { target: 'можливий', ua: 'possible', transcription: '' },
    { target: 'цілий', ua: 'whole', transcription: '' },
    { target: 'минулий', ua: 'past', transcription: '' },
    { target: 'білий', ua: 'white', transcription: '' },
    { target: 'чорний', ua: 'black', transcription: '' },
    { target: 'особливий', ua: 'special', transcription: '' },
    { target: 'легкий', ua: 'easy', transcription: '' },
    { target: 'особистий', ua: 'personal', transcription: '' },
    { target: 'бідний', ua: 'poor', transcription: '' },
    { target: 'багатий', ua: 'rich', transcription: '' },
    { target: 'схожий', ua: 'similar', transcription: '' },
    { target: 'головний', ua: 'main', transcription: '' },
    { target: 'необхідний', ua: 'necessary', transcription: '' },
    { target: 'позитивний', ua: 'positive', transcription: '' },
    { target: 'безпечний', ua: 'safe', transcription: '' },
    { target: 'широкий', ua: 'wide', transcription: '' },
    { target: 'далекий', ua: 'far', transcription: '' },
    { target: 'швидкий', ua: 'fast', transcription: '' },
    { target: 'певний', ua: 'certain', transcription: '' },
    { target: 'близький', ua: 'near', transcription: '' },
    { target: 'серйозний', ua: 'serious', transcription: '' },
    { target: 'імовірний', ua: 'likely', transcription: '' },
    { target: 'центральний', ua: 'central', transcription: '' },
    { target: 'кінцевий', ua: 'final', transcription: '' },
    { target: 'людський', ua: 'human', transcription: '' },
    { target: 'загальний', ua: 'general', transcription: '' },
    { target: 'звичайний', ua: 'common', transcription: '' },
    { target: 'прямий', ua: 'direct', transcription: '' },
    { target: 'красивий', ua: 'beautiful', transcription: '' },
    { target: 'червоний', ua: 'red', transcription: '' },
    { target: 'синій', ua: 'blue', transcription: '' },
    { target: 'зелений', ua: 'green', transcription: '' },
    { target: 'жовтий', ua: 'yellow', transcription: '' },
    { target: 'фіолетовий', ua: 'purple', transcription: '' },
    { target: 'помаранчевий', ua: 'orange', transcription: '' },
    { target: 'сірий', ua: 'grey', transcription: '' },
    { target: 'коричневий', ua: 'brown', transcription: '' },
    { target: 'живий', ua: 'alive', transcription: '' },
    { target: 'мертвий', ua: 'dead', transcription: '' },
    { target: 'злий', ua: 'angry', transcription: '' },
    { target: 'наляканий', ua: 'afraid', transcription: '' },
    { target: 'самотній', ua: 'alone', transcription: '' },
    { target: 'дивовижний', ua: 'amazing', transcription: '' },
    { target: 'стародавній', ua: 'ancient', transcription: '' },
    { target: 'яскравий', ua: 'bright', transcription: '' },
    { target: 'зайнятий', ua: 'busy', transcription: '' },
    { target: 'обережний', ua: 'careful', transcription: '' },
    { target: 'дешевий', ua: 'cheap', transcription: '' },
    { target: 'дорогий', ua: 'expensive', transcription: '' },
    { target: 'відомий', ua: 'famous', transcription: '' },
    { target: 'іноземний', ua: 'foreign', transcription: '' },
    { target: 'здоровий', ua: 'healthy', transcription: '' },
    { target: 'чесний', ua: 'honest', transcription: '' },
    { target: 'голодний', ua: 'hungry', transcription: '' },
    { target: 'лагідний', ua: 'kind', transcription: '' },
    { target: 'ледачий', ua: 'lazy', transcription: '' },
    { target: 'везучий', ua: 'lucky', transcription: '' },
    { target: 'шумний', ua: 'noisy', transcription: '' },
    { target: 'тихий', ua: 'quiet', transcription: '' },
    { target: 'гострий', ua: 'sharp', transcription: '' },
    { target: 'хворий', ua: 'sick', transcription: '' },
    { target: "м'який", ua: 'soft', transcription: '' },
    { target: 'солодкий', ua: 'sweet', transcription: '' },
    { target: 'жахливий', ua: 'terrible', transcription: '' },
    { target: 'тонкий', ua: 'thin', transcription: '' },
    { target: 'потворний', ua: 'ugly', transcription: '' },
    { target: 'корисний', ua: 'useful', transcription: '' },
    { target: 'слабкий', ua: 'weak', transcription: '' },
    { target: 'мудрий', ua: 'wise', transcription: '' },
  ],
  'adjective',
);

// ─── Прислівники ──────────────────────────────────────────────────────────────

const ADVERBS_UA = tag(
  [
    { target: 'дуже', ua: 'very', transcription: '' },
    { target: 'також', ua: 'also', transcription: '' },
    { target: 'просто', ua: 'just', transcription: '' },
    { target: 'тільки', ua: 'only', transcription: '' },
    { target: 'ще', ua: 'still', transcription: '' },
    { target: 'ніколи', ua: 'never', transcription: '' },
    { target: 'завжди', ua: 'always', transcription: '' },
    { target: 'часто', ua: 'often', transcription: '' },
    { target: 'разом', ua: 'together', transcription: '' },
    { target: 'вже', ua: 'already', transcription: '' },
    { target: 'знову', ua: 'again', transcription: '' },
    { target: 'майже', ua: 'almost', transcription: '' },
    { target: 'над', ua: 'above', transcription: '' },
    { target: 'навколо', ua: 'around', transcription: '' },
    { target: 'один раз', ua: 'once', transcription: '' },
    { target: 'теж', ua: 'too', transcription: '' },
    { target: 'геть', ua: 'away', transcription: '' },
    { target: 'тому', ua: 'ago', transcription: '' },
    { target: 'можливо', ua: 'perhaps', transcription: '' },
    { target: 'раптово', ua: 'suddenly', transcription: '' },
    { target: 'особливо', ua: 'especially', transcription: '' },
    { target: 'точно', ua: 'exactly', transcription: '' },
    { target: 'досить', ua: 'rather', transcription: '' },
    { target: 'незабаром', ua: 'soon', transcription: '' },
    { target: 'нещодавно', ua: 'recently', transcription: '' },
    { target: 'мабуть', ua: 'probably', transcription: '' },
    { target: 'зазвичай', ua: 'usually', transcription: '' },
    { target: 'швидко', ua: 'quickly', transcription: '' },
    { target: 'повільно', ua: 'slowly', transcription: '' },
    { target: 'нарешті', ua: 'finally', transcription: '' },
    { target: 'справді', ua: 'really', transcription: '' },
    { target: 'насправді', ua: 'actually', transcription: '' },
    { target: 'звичайно', ua: 'certainly', transcription: '' },
    { target: 'повністю', ua: 'completely', transcription: '' },
    { target: 'безпосередньо', ua: 'directly', transcription: '' },
    { target: 'легко', ua: 'easily', transcription: '' },
    { target: 'загалом', ua: 'generally', transcription: '' },
    { target: 'негайно', ua: 'immediately', transcription: '' },
    { target: 'чітко', ua: 'clearly', transcription: '' },
    { target: 'обережно', ua: 'carefully', transcription: '' },
    { target: 'глибоко', ua: 'deeply', transcription: '' },
    { target: 'гучно', ua: 'loudly', transcription: '' },
    { target: 'сильно', ua: 'strongly', transcription: '' },
    { target: 'надзвичайно', ua: 'highly', transcription: '' },
    { target: 'широко', ua: 'widely', transcription: '' },
  ],
  'adverb',
);

// ─── Exports ───────────────────────────────────────────────────────────────────

export const WORDS_UA: Word[] = [...VERBS_UA, ...NOUNS_UA, ...ADJECTIVES_UA, ...ADVERBS_UA];

export const WORDS_UA_BY_CATEGORY: Record<WordCategory, Word[]> = {
  verb: VERBS_UA,
  noun: NOUNS_UA,
  adjective: ADJECTIVES_UA,
  adverb: ADVERBS_UA,
};
