export type WordCategory = 'verb' | 'noun' | 'adjective' | 'adverb';

export interface Word {
  en: string;
  ua: string;
  category: WordCategory;
}

function tag(words: { en: string; ua: string }[], category: WordCategory): Word[] {
  return words.map((w) => ({ ...w, category }));
}

// ─── Дієслова ─────────────────────────────────────────────────────────────────

const VERBS = tag(
  [
    { en: 'be', ua: 'бути' },
    { en: 'have', ua: 'мати' },
    { en: 'do', ua: 'робити' },
    { en: 'say', ua: 'казати' },
    { en: 'get', ua: 'отримувати' },
    { en: 'make', ua: 'виготовляти' },
    { en: 'go', ua: 'іти' },
    { en: 'know', ua: 'знати' },
    { en: 'take', ua: 'брати' },
    { en: 'see', ua: 'бачити' },
    { en: 'come', ua: 'приходити' },
    { en: 'think', ua: 'думати' },
    { en: 'look', ua: 'дивитися' },
    { en: 'want', ua: 'хотіти' },
    { en: 'give', ua: 'давати' },
    { en: 'use', ua: 'використовувати' },
    { en: 'find', ua: 'знаходити' },
    { en: 'tell', ua: 'розповідати' },
    { en: 'ask', ua: 'запитувати' },
    { en: 'seem', ua: 'здаватися' },
    { en: 'feel', ua: 'відчувати' },
    { en: 'try', ua: 'намагатися' },
    { en: 'leave', ua: 'залишати' },
    { en: 'call', ua: 'телефонувати' },
    { en: 'keep', ua: 'зберігати' },
    { en: 'let', ua: 'дозволяти' },
    { en: 'begin', ua: 'починати' },
    { en: 'show', ua: 'показувати' },
    { en: 'hear', ua: 'чути' },
    { en: 'play', ua: 'грати' },
    { en: 'run', ua: 'бігти' },
    { en: 'move', ua: 'рухатися' },
    { en: 'live', ua: 'жити' },
    { en: 'believe', ua: 'вірити' },
    { en: 'hold', ua: 'тримати' },
    { en: 'bring', ua: 'приносити' },
    { en: 'happen', ua: 'відбуватися' },
    { en: 'write', ua: 'писати' },
    { en: 'provide', ua: 'забезпечувати' },
    { en: 'sit', ua: 'сидіти' },
    { en: 'stand', ua: 'стояти' },
    { en: 'lose', ua: 'втрачати' },
    { en: 'pay', ua: 'платити' },
    { en: 'meet', ua: 'зустрічати' },
    { en: 'include', ua: 'включати' },
    { en: 'continue', ua: 'продовжувати' },
    { en: 'set', ua: 'встановлювати' },
    { en: 'learn', ua: 'вчитися' },
    { en: 'lead', ua: 'вести' },
    { en: 'understand', ua: 'розуміти' },
    { en: 'watch', ua: 'спостерігати' },
    { en: 'follow', ua: 'слідувати' },
    { en: 'stop', ua: 'зупинятися' },
    { en: 'create', ua: 'створювати' },
    { en: 'speak', ua: 'розмовляти' },
    { en: 'read', ua: 'читати' },
    { en: 'spend', ua: 'витрачати' },
    { en: 'grow', ua: 'рости' },
    { en: 'open', ua: 'відкривати' },
    { en: 'walk', ua: 'ходити' },
    { en: 'win', ua: 'перемагати' },
    { en: 'offer', ua: 'пропонувати' },
    { en: 'remember', ua: "пам'ятати" },
    { en: 'consider', ua: 'вважати' },
    { en: 'appear', ua: "з'являтися" },
    { en: 'buy', ua: 'купувати' },
    { en: 'wait', ua: 'чекати' },
    { en: 'serve', ua: 'служити' },
    { en: 'send', ua: 'відправляти' },
    { en: 'expect', ua: 'очікувати' },
    { en: 'build', ua: 'будувати' },
    { en: 'stay', ua: 'залишатися' },
    { en: 'fall', ua: 'падати' },
    { en: 'cut', ua: 'різати' },
    { en: 'reach', ua: 'досягати' },
    { en: 'suggest', ua: 'радити' },
    { en: 'raise', ua: 'піднімати' },
    { en: 'pass', ua: 'проходити' },
    { en: 'sell', ua: 'продавати' },
    { en: 'require', ua: 'вимагати' },
    { en: 'report', ua: 'повідомляти' },
    { en: 'decide', ua: 'вирішувати' },
    { en: 'pull', ua: 'тягнути' },
    { en: 'break', ua: 'розбивати' },
    { en: 'carry', ua: 'нести' },
    { en: 'throw', ua: 'кидати' },
    { en: 'catch', ua: 'ловити' },
    { en: 'push', ua: 'штовхати' },
    { en: 'turn', ua: 'повертати' },
    { en: 'return', ua: 'повертатися' },
    { en: 'explain', ua: 'пояснювати' },
    { en: 'choose', ua: 'вибирати' },
    { en: 'close', ua: 'закривати' },
    { en: 'drive', ua: 'водити' },
    { en: 'eat', ua: 'їсти' },
    { en: 'drink', ua: 'пити' },
    { en: 'sleep', ua: 'спати' },
    { en: 'help', ua: 'допомагати' },
    { en: 'start', ua: 'запускати' },
    { en: 'add', ua: 'додавати' },
    { en: 'allow', ua: 'дозволяти' },
    { en: 'answer', ua: 'відповідати' },
    { en: 'check', ua: 'перевіряти' },
    { en: 'cover', ua: 'покривати' },
    { en: 'enter', ua: 'входити' },
    { en: 'fight', ua: 'боротися' },
    { en: 'fly', ua: 'літати' },
    { en: 'forget', ua: 'забувати' },
    { en: 'hit', ua: 'вдаряти' },
    { en: 'jump', ua: 'стрибати' },
    { en: 'kill', ua: 'вбивати' },
    { en: 'laugh', ua: 'сміятися' },
    { en: 'lie', ua: 'брехати' },
    { en: 'lift', ua: 'підіймати' },
    { en: 'listen', ua: 'слухати' },
    { en: 'miss', ua: 'скучати' },
    { en: 'notice', ua: 'помічати' },
    { en: 'prefer', ua: 'надавати перевагу' },
    { en: 'prepare', ua: 'готувати' },
    { en: 'prevent', ua: 'запобігати' },
    { en: 'protect', ua: 'захищати' },
    { en: 'prove', ua: 'доводити' },
    { en: 'reduce', ua: 'зменшувати' },
    { en: 'replace', ua: 'замінювати' },
    { en: 'save', ua: 'рятувати' },
    { en: 'share', ua: 'ділитися' },
    { en: 'smile', ua: 'посміхатися' },
    { en: 'solve', ua: "розв'язувати" },
    { en: 'support', ua: 'підтримувати' },
    { en: 'surprise', ua: 'дивувати' },
    { en: 'survive', ua: 'виживати' },
    { en: 'teach', ua: 'навчати' },
    { en: 'touch', ua: 'торкатися' },
    { en: 'travel', ua: 'подорожувати' },
    { en: 'trust', ua: 'довіряти' },
    { en: 'visit', ua: 'відвідувати' },
    { en: 'wake', ua: 'прокидатися' },
    { en: 'wear', ua: 'носити' },
    { en: 'wish', ua: 'бажати' },
    { en: 'work', ua: 'працювати' },
    { en: 'worry', ua: 'турбуватися' },
    { en: 'accept', ua: 'приймати' },
    { en: 'achieve', ua: 'здобувати' },
    { en: 'avoid', ua: 'уникати' },
    { en: 'celebrate', ua: 'святкувати' },
    { en: 'collect', ua: 'збирати' },
    { en: 'compare', ua: 'порівнювати' },
    { en: 'connect', ua: "з'єднувати" },
    { en: 'convince', ua: 'переконувати' },
    { en: 'count', ua: 'рахувати' },
  ],
  'verb',
);

// ─── Іменники ─────────────────────────────────────────────────────────────────

const NOUNS = tag(
  [
    { en: 'time', ua: 'час' },
    { en: 'person', ua: 'людина' },
    { en: 'year', ua: 'рік' },
    { en: 'way', ua: 'спосіб' },
    { en: 'day', ua: 'день' },
    { en: 'thing', ua: 'річ' },
    { en: 'man', ua: 'чоловік' },
    { en: 'world', ua: 'світ' },
    { en: 'life', ua: 'життя' },
    { en: 'hand', ua: 'рука' },
    { en: 'part', ua: 'частина' },
    { en: 'place', ua: 'місце' },
    { en: 'week', ua: 'тиждень' },
    { en: 'company', ua: 'компанія' },
    { en: 'group', ua: 'група' },
    { en: 'problem', ua: 'проблема' },
    { en: 'fact', ua: 'факт' },
    { en: 'money', ua: 'гроші' },
    { en: 'number', ua: 'число' },
    { en: 'night', ua: 'ніч' },
    { en: 'city', ua: 'місто' },
    { en: 'name', ua: "ім'я" },
    { en: 'home', ua: 'дім' },
    { en: 'water', ua: 'вода' },
    { en: 'room', ua: 'кімната' },
    { en: 'mother', ua: 'мати' },
    { en: 'area', ua: 'територія' },
    { en: 'family', ua: "сім'я" },
    { en: 'body', ua: 'тіло' },
    { en: 'eye', ua: 'око' },
    { en: 'food', ua: 'їжа' },
    { en: 'child', ua: 'дитина' },
    { en: 'door', ua: 'двері' },
    { en: 'country', ua: 'країна' },
    { en: 'question', ua: 'питання' },
    { en: 'head', ua: 'голова' },
    { en: 'heart', ua: 'серце' },
    { en: 'idea', ua: 'ідея' },
    { en: 'school', ua: 'школа' },
    { en: 'story', ua: 'оповідання' },
    { en: 'book', ua: 'книга' },
    { en: 'street', ua: 'вулиця' },
    { en: 'moment', ua: 'мить' },
    { en: 'face', ua: 'обличчя' },
    { en: 'friend', ua: 'друг' },
    { en: 'morning', ua: 'ранок' },
    { en: 'girl', ua: 'дівчина' },
    { en: 'boy', ua: 'хлопець' },
    { en: 'power', ua: 'влада' },
    { en: 'word', ua: 'слово' },
    { en: 'road', ua: 'дорога' },
    { en: 'month', ua: 'місяць' },
    { en: 'line', ua: 'лінія' },
    { en: 'government', ua: 'уряд' },
    { en: 'car', ua: 'автомобіль' },
    { en: 'town', ua: 'містечко' },
    { en: 'language', ua: 'мова' },
    { en: 'level', ua: 'рівень' },
    { en: 'air', ua: 'повітря' },
    { en: 'hour', ua: 'година' },
    { en: 'game', ua: 'гра' },
    { en: 'fire', ua: 'вогонь' },
    { en: 'land', ua: 'земля' },
    { en: 'age', ua: 'вік' },
    { en: 'voice', ua: 'голос' },
    { en: 'color', ua: 'колір' },
    { en: 'sound', ua: 'звук' },
    { en: 'news', ua: 'новини' },
    { en: 'light', ua: 'світло' },
    { en: 'type', ua: 'тип' },
    { en: 'class', ua: 'клас' },
    { en: 'period', ua: 'період' },
    { en: 'building', ua: 'будівля' },
    { en: 'field', ua: 'поле' },
    { en: 'business', ua: 'бізнес' },
    { en: 'picture', ua: 'картина' },
    { en: 'space', ua: 'простір' },
    { en: 'view', ua: 'вид' },
    { en: 'house', ua: 'будинок' },
    { en: 'team', ua: 'команда' },
    { en: 'service', ua: 'служба' },
    { en: 'price', ua: 'ціна' },
    { en: 'hair', ua: 'волосся' },
    { en: 'rest', ua: 'відпочинок' },
    { en: 'step', ua: 'крок' },
    { en: 'law', ua: 'закон' },
    { en: 'century', ua: 'сторіччя' },
    { en: 'state', ua: 'держава' },
    { en: 'war', ua: 'війна' },
    { en: 'party', ua: 'партія' },
    { en: 'society', ua: 'суспільство' },
    { en: 'music', ua: 'музика' },
    { en: 'office', ua: 'офіс' },
    { en: 'position', ua: 'позиція' },
    { en: 'role', ua: 'роль' },
    { en: 'president', ua: 'президент' },
    { en: 'decision', ua: 'рішення' },
    { en: 'reason', ua: 'причина' },
    { en: 'nature', ua: 'природа' },
    { en: 'system', ua: 'система' },
    { en: 'love', ua: 'кохання' },
    { en: 'plan', ua: 'план' },
    { en: 'art', ua: 'мистецтво' },
    { en: 'development', ua: 'розвиток' },
    { en: 'security', ua: 'безпека' },
    { en: 'future', ua: 'майбутнє' },
    { en: 'chance', ua: 'шанс' },
    { en: 'change', ua: 'зміна' },
    { en: 'community', ua: 'спільнота' },
    { en: 'center', ua: 'центр' },
    { en: 'result', ua: 'результат' },
    { en: 'model', ua: 'модель' },
    { en: 'economy', ua: 'економіка' },
    { en: 'energy', ua: 'енергія' },
    { en: 'experience', ua: 'досвід' },
    { en: 'education', ua: 'освіта' },
    { en: 'success', ua: 'успіх' },
    { en: 'value', ua: 'цінність' },
    { en: 'history', ua: 'історія' },
    { en: 'paper', ua: 'папір' },
    { en: 'research', ua: 'дослідження' },
    { en: 'ability', ua: 'здатність' },
    { en: 'relationship', ua: 'стосунки' },
    { en: 'evening', ua: 'вечір' },
    { en: 'attention', ua: 'увага' },
    { en: 'culture', ua: 'культура' },
    { en: 'truth', ua: 'правда' },
    { en: 'leader', ua: 'лідер' },
    { en: 'student', ua: 'студент' },
    { en: 'teacher', ua: 'вчитель' },
    { en: 'parent', ua: 'батьки' },
    { en: 'window', ua: 'вікно' },
    { en: 'table', ua: 'стіл' },
    { en: 'chair', ua: 'стілець' },
    { en: 'bed', ua: 'ліжко' },
    { en: 'sun', ua: 'сонце' },
    { en: 'tree', ua: 'дерево' },
    { en: 'river', ua: 'річка' },
    { en: 'sea', ua: 'море' },
    { en: 'mountain', ua: 'гора' },
    { en: 'sky', ua: 'небо' },
    { en: 'animal', ua: 'тварина' },
    { en: 'dog', ua: 'собака' },
    { en: 'cat', ua: 'кіт' },
    { en: 'bird', ua: 'птах' },
    { en: 'fish', ua: 'риба' },
    { en: 'flower', ua: 'квітка' },
    { en: 'garden', ua: 'сад' },
    { en: 'store', ua: 'магазин' },
    { en: 'hospital', ua: 'лікарня' },
    // Додаткові іменники
    { en: 'letter', ua: 'буква' },
    { en: 'doctor', ua: 'лікар' },
    { en: 'police', ua: 'поліція' },
    { en: 'soldier', ua: 'солдат' },
    { en: 'king', ua: 'король' },
    { en: 'queen', ua: 'королева' },
    { en: 'baby', ua: 'немовля' },
    { en: 'brother', ua: 'брат' },
    { en: 'sister', ua: 'сестра' },
    { en: 'father', ua: 'батько' },
    { en: 'wife', ua: 'дружина' },
    { en: 'son', ua: 'син' },
    { en: 'daughter', ua: 'дочка' },
    { en: 'neighbor', ua: 'сусід' },
    { en: 'enemy', ua: 'ворог' },
    { en: 'church', ua: 'церква' },
    { en: 'library', ua: 'бібліотека' },
    { en: 'airport', ua: 'аеропорт' },
    { en: 'station', ua: 'станція' },
    { en: 'army', ua: 'армія' },
    { en: 'forest', ua: 'ліс' },
    { en: 'lake', ua: 'озеро' },
    { en: 'beach', ua: 'пляж' },
    { en: 'rain', ua: 'дощ' },
    { en: 'snow', ua: 'сніг' },
    { en: 'star', ua: 'зірка' },
  ],
  'noun',
);

// ─── Прикметники ──────────────────────────────────────────────────────────────

const ADJECTIVES = tag(
  [
    { en: 'good', ua: 'добрий' },
    { en: 'new', ua: 'новий' },
    { en: 'first', ua: 'перший' },
    { en: 'last', ua: 'останній' },
    { en: 'long', ua: 'довгий' },
    { en: 'great', ua: 'чудовий' },
    { en: 'little', ua: 'маленький' },
    { en: 'own', ua: 'власний' },
    { en: 'other', ua: 'інший' },
    { en: 'old', ua: 'старий' },
    { en: 'right', ua: 'правильний' },
    { en: 'big', ua: 'великий' },
    { en: 'high', ua: 'високий' },
    { en: 'different', ua: 'різний' },
    { en: 'small', ua: 'малий' },
    { en: 'large', ua: 'величезний' },
    { en: 'next', ua: 'наступний' },
    { en: 'early', ua: 'ранній' },
    { en: 'young', ua: 'молодий' },
    { en: 'important', ua: 'важливий' },
    { en: 'public', ua: 'публічний' },
    { en: 'bad', ua: 'поганий' },
    { en: 'same', ua: 'однаковий' },
    { en: 'able', ua: 'здатний' },
    { en: 'real', ua: 'справжній' },
    { en: 'best', ua: 'найкращий' },
    { en: 'free', ua: 'вільний' },
    { en: 'sure', ua: 'впевнений' },
    { en: 'better', ua: 'кращий' },
    { en: 'true', ua: 'правдивий' },
    { en: 'hard', ua: 'складний' },
    { en: 'low', ua: 'низький' },
    { en: 'short', ua: 'короткий' },
    { en: 'clear', ua: 'чіткий' },
    { en: 'recent', ua: 'нещодавній' },
    { en: 'left', ua: 'лівий' },
    { en: 'political', ua: 'політичний' },
    { en: 'social', ua: 'соціальний' },
    { en: 'economic', ua: 'економічний' },
    { en: 'local', ua: 'місцевий' },
    { en: 'national', ua: 'національний' },
    { en: 'full', ua: 'повний' },
    { en: 'hot', ua: 'гарячий' },
    { en: 'dark', ua: 'темний' },
    { en: 'strong', ua: 'сильний' },
    { en: 'deep', ua: 'глибокий' },
    { en: 'heavy', ua: 'важкий' },
    { en: 'cold', ua: 'холодний' },
    { en: 'warm', ua: 'теплий' },
    { en: 'clean', ua: 'чистий' },
    { en: 'dry', ua: 'сухий' },
    { en: 'wrong', ua: 'неправильний' },
    { en: 'happy', ua: 'щасливий' },
    { en: 'late', ua: 'пізній' },
    { en: 'ready', ua: 'готовий' },
    { en: 'simple', ua: 'простий' },
    { en: 'possible', ua: 'можливий' },
    { en: 'whole', ua: 'цілий' },
    { en: 'past', ua: 'минулий' },
    { en: 'white', ua: 'білий' },
    { en: 'black', ua: 'чорний' },
    { en: 'special', ua: 'особливий' },
    { en: 'easy', ua: 'легкий' },
    { en: 'personal', ua: 'особистий' },
    { en: 'poor', ua: 'бідний' },
    { en: 'rich', ua: 'багатий' },
    { en: 'similar', ua: 'схожий' },
    { en: 'main', ua: 'головний' },
    { en: 'necessary', ua: 'необхідний' },
    { en: 'positive', ua: 'позитивний' },
    { en: 'safe', ua: 'безпечний' },
    { en: 'wide', ua: 'широкий' },
    { en: 'far', ua: 'далекий' },
    { en: 'fast', ua: 'швидкий' },
    { en: 'certain', ua: 'певний' },
    { en: 'near', ua: 'близький' },
    { en: 'difficult', ua: 'непростий' },
    { en: 'serious', ua: 'серйозний' },
    { en: 'likely', ua: 'імовірний' },
    { en: 'central', ua: 'центральний' },
    { en: 'final', ua: 'кінцевий' },
    { en: 'human', ua: 'людський' },
    { en: 'general', ua: 'загальний' },
    { en: 'common', ua: 'звичайний' },
    { en: 'direct', ua: 'прямий' },
    { en: 'beautiful', ua: 'красивий' },
    { en: 'red', ua: 'червоний' },
    { en: 'blue', ua: 'синій' },
    { en: 'green', ua: 'зелений' },
    { en: 'yellow', ua: 'жовтий' },
    { en: 'purple', ua: 'фіолетовий' },
    { en: 'orange', ua: 'помаранчевий' },
    { en: 'grey', ua: 'сірий' },
    { en: 'brown', ua: 'коричневий' },
    { en: 'alive', ua: 'живий' },
    { en: 'dead', ua: 'мертвий' },
    { en: 'angry', ua: 'сердитий' },
    { en: 'afraid', ua: 'наляканий' },
    { en: 'alone', ua: 'самотній' },
    { en: 'amazing', ua: 'дивовижний' },
    { en: 'ancient', ua: 'стародавній' },
    { en: 'bright', ua: 'яскравий' },
    { en: 'busy', ua: 'зайнятий' },
    { en: 'careful', ua: 'обережний' },
    { en: 'cheap', ua: 'дешевий' },
    { en: 'expensive', ua: 'дорогий' },
    { en: 'famous', ua: 'відомий' },
    { en: 'foreign', ua: 'іноземний' },
    { en: 'healthy', ua: 'здоровий' },
    { en: 'honest', ua: 'чесний' },
    { en: 'hungry', ua: 'голодний' },
    { en: 'kind', ua: 'лагідний' },
    { en: 'lazy', ua: 'ледачий' },
    { en: 'lucky', ua: 'удачливий' },
    { en: 'noisy', ua: 'гамірний' },
    { en: 'quiet', ua: 'тихий' },
    { en: 'sharp', ua: 'гострий' },
    { en: 'sick', ua: 'хворий' },
    { en: 'soft', ua: "м'який" },
    { en: 'sweet', ua: 'солодкий' },
    { en: 'terrible', ua: 'жахливий' },
    { en: 'thin', ua: 'тонкий' },
    { en: 'ugly', ua: 'потворний' },
    { en: 'useful', ua: 'корисний' },
    { en: 'weak', ua: 'слабкий' },
    { en: 'wise', ua: 'мудрий' },
  ],
  'adjective',
);

// ─── Прислівники ──────────────────────────────────────────────────────────────

const ADVERBS = tag(
  [
    { en: 'very', ua: 'дуже' },
    { en: 'also', ua: 'також' },
    { en: 'just', ua: 'просто' },
    { en: 'only', ua: 'тільки' },
    { en: 'still', ua: 'ще' },
    { en: 'never', ua: 'ніколи' },
    { en: 'always', ua: 'завжди' },
    { en: 'often', ua: 'часто' },
    { en: 'together', ua: 'разом' },
    { en: 'already', ua: 'вже' },
    { en: 'again', ua: 'знову' },
    { en: 'almost', ua: 'майже' },
    { en: 'above', ua: 'вище' },
    { en: 'around', ua: 'навколо' },
    { en: 'once', ua: 'одного разу' },
    { en: 'too', ua: 'теж' },
    { en: 'away', ua: 'геть' },
    { en: 'ago', ua: 'тому' },
    { en: 'yet', ua: 'досі' },
    { en: 'perhaps', ua: 'можливо' },
    { en: 'suddenly', ua: 'раптово' },
    { en: 'especially', ua: 'особливо' },
    { en: 'exactly', ua: 'точно' },
    { en: 'rather', ua: 'досить' },
    { en: 'soon', ua: 'незабаром' },
    { en: 'recently', ua: 'нещодавно' },
    { en: 'probably', ua: 'мабуть' },
    { en: 'usually', ua: 'зазвичай' },
    { en: 'quickly', ua: 'швидко' },
    { en: 'slowly', ua: 'повільно' },
    { en: 'finally', ua: 'нарешті' },
    { en: 'really', ua: 'справді' },
    { en: 'actually', ua: 'насправді' },
    { en: 'certainly', ua: 'звичайно' },
    { en: 'completely', ua: 'повністю' },
    { en: 'directly', ua: 'безпосередньо' },
    { en: 'easily', ua: 'легко' },
    { en: 'generally', ua: 'загалом' },
    { en: 'immediately', ua: 'негайно' },
    { en: 'simply', ua: 'по-простому' },
    { en: 'clearly', ua: 'чітко' },
    { en: 'carefully', ua: 'обережно' },
    { en: 'deeply', ua: 'глибоко' },
    { en: 'loudly', ua: 'гучно' },
    { en: 'softly', ua: 'тихесенько' },
    { en: 'freely', ua: 'вільно' },
    { en: 'strongly', ua: 'сильно' },
    { en: 'highly', ua: 'надзвичайно' },
    { en: 'widely', ua: 'широко' },
    { en: 'nearly', ua: 'майже' },
  ],
  'adverb',
);

// ─── Exports ──────────────────────────────────────────────────────────────────

export const WORDS: Word[] = [...VERBS, ...NOUNS, ...ADJECTIVES, ...ADVERBS];

export const WORDS_BY_CATEGORY: Record<WordCategory, Word[]> = {
  verb: VERBS,
  noun: NOUNS,
  adjective: ADJECTIVES,
  adverb: ADVERBS,
};
