export type WordCategory = 'verb' | 'noun' | 'adjective' | 'adverb';

export interface Word {
  en: string;
  ua: string;
  transcription: string;
  category: WordCategory;
}

function tag(
  words: { en: string; ua: string; transcription: string }[],
  category: WordCategory,
): Word[] {
  return words.map((w) => ({ ...w, category }));
}

// ─── Дієслова ─────────────────────────────────────────────────────────────────

const VERBS = tag(
  [
    { en: 'be', ua: 'бути', transcription: '[biː]' },
    { en: 'have', ua: 'мати', transcription: '[hæv]' },
    { en: 'do', ua: 'робити', transcription: '[duː]' },
    { en: 'say', ua: 'казати', transcription: '[seɪ]' },
    { en: 'get', ua: 'отримувати', transcription: '[ɡet]' },
    { en: 'make', ua: 'робити', transcription: '[meɪk]' },
    { en: 'go', ua: 'іти', transcription: '[ɡoʊ]' },
    { en: 'know', ua: 'знати', transcription: '[noʊ]' },
    { en: 'take', ua: 'брати', transcription: '[teɪk]' },
    { en: 'see', ua: 'бачити', transcription: '[siː]' },
    { en: 'come', ua: 'приходити', transcription: '[kʌm]' },
    { en: 'think', ua: 'думати', transcription: '[θɪŋk]' },
    { en: 'look', ua: 'дивитися', transcription: '[lʊk]' },
    { en: 'want', ua: 'хотіти', transcription: '[wɑːnt]' },
    { en: 'give', ua: 'давати', transcription: '[ɡɪv]' },
    { en: 'use', ua: 'використовувати', transcription: '[juːz]' },
    { en: 'find', ua: 'знаходити', transcription: '[faɪnd]' },
    { en: 'tell', ua: 'розповідати', transcription: '[tel]' },
    { en: 'ask', ua: 'запитувати', transcription: '[æsk]' },
    { en: 'seem', ua: 'здаватися', transcription: '[siːm]' },
    { en: 'feel', ua: 'відчувати', transcription: '[fiːl]' },
    { en: 'try', ua: 'намагатися', transcription: '[traɪ]' },
    { en: 'leave', ua: 'залишати', transcription: '[liːv]' },
    { en: 'call', ua: 'телефонувати', transcription: '[kɔːl]' },
    { en: 'keep', ua: 'тримати', transcription: '[kiːp]' },
    { en: 'let', ua: 'дозволяти', transcription: '[let]' },
    { en: 'begin', ua: 'починати', transcription: '[bɪˈɡɪn]' },
    { en: 'show', ua: 'показувати', transcription: '[ʃoʊ]' },
    { en: 'hear', ua: 'чути', transcription: '[hɪr]' },
    { en: 'play', ua: 'грати', transcription: '[pleɪ]' },
    { en: 'run', ua: 'бігти', transcription: '[rʌn]' },
    { en: 'move', ua: 'рухатися', transcription: '[muːv]' },
    { en: 'live', ua: 'жити', transcription: '[lɪv]' },
    { en: 'believe', ua: 'вірити', transcription: '[bɪˈliːv]' },
    { en: 'hold', ua: 'тримати', transcription: '[hoʊld]' },
    { en: 'bring', ua: 'приносити', transcription: '[brɪŋ]' },
    { en: 'happen', ua: 'відбуватися', transcription: '[ˈhæpən]' },
    { en: 'write', ua: 'писати', transcription: '[raɪt]' },
    { en: 'provide', ua: 'забезпечувати', transcription: '[prəˈvaɪd]' },
    { en: 'sit', ua: 'сидіти', transcription: '[sɪt]' },
    { en: 'stand', ua: 'стояти', transcription: '[stænd]' },
    { en: 'lose', ua: 'втрачати', transcription: '[luːz]' },
    { en: 'pay', ua: 'платити', transcription: '[peɪ]' },
    { en: 'meet', ua: 'зустрічати', transcription: '[miːt]' },
    { en: 'include', ua: 'включати', transcription: '[ɪnˈkluːd]' },
    { en: 'continue', ua: 'продовжувати', transcription: '[kənˈtɪnjuː]' },
    { en: 'set', ua: 'встановлювати', transcription: '[set]' },
    { en: 'learn', ua: 'вчитися', transcription: '[lɜːrn]' },
    { en: 'lead', ua: 'вести', transcription: '[liːd]' },
    { en: 'understand', ua: 'розуміти', transcription: '[ˌʌndərˈstænd]' },
    { en: 'watch', ua: 'дивитися', transcription: '[wɑːtʃ]' },
    { en: 'follow', ua: 'слідувати', transcription: '[ˈfɑːloʊ]' },
    { en: 'stop', ua: 'зупинятися', transcription: '[stɑːp]' },
    { en: 'create', ua: 'створювати', transcription: '[kriˈeɪt]' },
    { en: 'speak', ua: 'розмовляти', transcription: '[spiːk]' },
    { en: 'read', ua: 'читати', transcription: '[riːd]' },
    { en: 'spend', ua: 'витрачати', transcription: '[spend]' },
    { en: 'grow', ua: 'рости', transcription: '[ɡroʊ]' },
    { en: 'open', ua: 'відкривати', transcription: '[ˈoʊpən]' },
    { en: 'walk', ua: 'ходити', transcription: '[wɔːk]' },
    { en: 'win', ua: 'перемагати', transcription: '[wɪn]' },
    { en: 'offer', ua: 'пропонувати', transcription: '[ˈɔːfər]' },
    { en: 'remember', ua: "пам'ятати", transcription: '[rɪˈmembər]' },
    { en: 'consider', ua: 'вважати', transcription: '[kənˈsɪdər]' },
    { en: 'appear', ua: "з'являтися", transcription: '[əˈpɪr]' },
    { en: 'buy', ua: 'купувати', transcription: '[baɪ]' },
    { en: 'wait', ua: 'чекати', transcription: '[weɪt]' },
    { en: 'serve', ua: 'обслуговувати', transcription: '[sɜːrv]' },
    { en: 'send', ua: 'відправляти', transcription: '[send]' },
    { en: 'expect', ua: 'очікувати', transcription: '[ɪkˈspekt]' },
    { en: 'build', ua: 'будувати', transcription: '[bɪld]' },
    { en: 'stay', ua: 'залишатися', transcription: '[steɪ]' },
    { en: 'fall', ua: 'падати', transcription: '[fɔːl]' },
    { en: 'cut', ua: 'різати', transcription: '[kʌt]' },
    { en: 'reach', ua: 'досягати', transcription: '[riːtʃ]' },
    { en: 'suggest', ua: 'пропонувати', transcription: '[səˈdʒest]' },
    { en: 'raise', ua: 'піднімати', transcription: '[reɪz]' },
    { en: 'pass', ua: 'проходити', transcription: '[pæs]' },
    { en: 'sell', ua: 'продавати', transcription: '[sel]' },
    { en: 'require', ua: 'вимагати', transcription: '[rɪˈkwaɪər]' },
    { en: 'report', ua: 'повідомляти', transcription: '[rɪˈpɔːrt]' },
    { en: 'decide', ua: 'вирішувати', transcription: '[dɪˈsaɪd]' },
    { en: 'pull', ua: 'тягнути', transcription: '[pʊl]' },
    { en: 'break', ua: 'розбивати', transcription: '[breɪk]' },
    { en: 'carry', ua: 'нести', transcription: '[ˈkæri]' },
    { en: 'throw', ua: 'кидати', transcription: '[θroʊ]' },
    { en: 'catch', ua: 'ловити', transcription: '[kætʃ]' },
    { en: 'push', ua: 'штовхати', transcription: '[pʊʃ]' },
    { en: 'turn', ua: 'повертати', transcription: '[tɜːrn]' },
    { en: 'return', ua: 'повертатися', transcription: '[rɪˈtɜːrn]' },
    { en: 'explain', ua: 'пояснювати', transcription: '[ɪkˈspleɪn]' },
    { en: 'choose', ua: 'вибирати', transcription: '[tʃuːz]' },
    { en: 'close', ua: 'закривати', transcription: '[kloʊz]' },
    { en: 'drive', ua: 'водити', transcription: '[draɪv]' },
    { en: 'eat', ua: 'їсти', transcription: '[iːt]' },
    { en: 'drink', ua: 'пити', transcription: '[drɪŋk]' },
    { en: 'sleep', ua: 'спати', transcription: '[sliːp]' },
    { en: 'help', ua: 'допомагати', transcription: '[help]' },
    { en: 'start', ua: 'починати', transcription: '[stɑːrt]' },
    { en: 'add', ua: 'додавати', transcription: '[æd]' },
    { en: 'allow', ua: 'дозволяти', transcription: '[əˈlaʊ]' },
    { en: 'answer', ua: 'відповідати', transcription: '[ˈænsər]' },
    { en: 'check', ua: 'перевіряти', transcription: '[tʃek]' },
    { en: 'cover', ua: 'покривати', transcription: '[ˈkʌvər]' },
    { en: 'enter', ua: 'входити', transcription: '[ˈentər]' },
    { en: 'fight', ua: 'боротися', transcription: '[faɪt]' },
    { en: 'fly', ua: 'літати', transcription: '[flaɪ]' },
    { en: 'forget', ua: 'забувати', transcription: '[fərˈɡet]' },
    { en: 'hit', ua: 'вдаряти', transcription: '[hɪt]' },
    { en: 'jump', ua: 'стрибати', transcription: '[dʒʌmp]' },
    { en: 'kill', ua: 'вбивати', transcription: '[kɪl]' },
    { en: 'laugh', ua: 'сміятися', transcription: '[læf]' },
    { en: 'lie', ua: 'брехати', transcription: '[laɪ]' },
    { en: 'lift', ua: 'підіймати', transcription: '[lɪft]' },
    { en: 'listen', ua: 'слухати', transcription: '[ˈlɪsən]' },
    { en: 'miss', ua: 'скучати', transcription: '[mɪs]' },
    { en: 'notice', ua: 'помічати', transcription: '[ˈnoʊtɪs]' },
    { en: 'prefer', ua: 'воліти', transcription: '[prɪˈfɜːr]' },
    { en: 'prepare', ua: 'готувати', transcription: '[prɪˈper]' },
    { en: 'prevent', ua: 'запобігати', transcription: '[prɪˈvent]' },
    { en: 'protect', ua: 'захищати', transcription: '[prəˈtekt]' },
    { en: 'prove', ua: 'доводити', transcription: '[pruːv]' },
    { en: 'reduce', ua: 'зменшувати', transcription: '[rɪˈduːs]' },
    { en: 'replace', ua: 'замінювати', transcription: '[rɪˈpleɪs]' },
    { en: 'save', ua: 'рятувати', transcription: '[seɪv]' },
    { en: 'share', ua: 'ділитися', transcription: '[ʃer]' },
    { en: 'smile', ua: 'посміхатися', transcription: '[smaɪl]' },
    { en: 'solve', ua: "розв'язувати", transcription: '[sɑːlv]' },
    { en: 'support', ua: 'підтримувати', transcription: '[səˈpɔːrt]' },
    { en: 'surprise', ua: 'дивувати', transcription: '[sərˈpraɪz]' },
    { en: 'survive', ua: 'виживати', transcription: '[sərˈvaɪv]' },
    { en: 'teach', ua: 'навчати', transcription: '[tiːtʃ]' },
    { en: 'touch', ua: 'торкатися', transcription: '[tʌtʃ]' },
    { en: 'travel', ua: 'подорожувати', transcription: '[ˈtrævəl]' },
    { en: 'trust', ua: 'довіряти', transcription: '[trʌst]' },
    { en: 'visit', ua: 'відвідувати', transcription: '[ˈvɪzɪt]' },
    { en: 'wake', ua: 'прокидатися', transcription: '[weɪk]' },
    { en: 'wear', ua: 'носити', transcription: '[wer]' },
    { en: 'wish', ua: 'бажати', transcription: '[wɪʃ]' },
    { en: 'work', ua: 'працювати', transcription: '[wɜːrk]' },
    { en: 'worry', ua: 'турбуватися', transcription: '[ˈwɜːri]' },
    { en: 'accept', ua: 'приймати', transcription: '[əkˈsept]' },
    { en: 'achieve', ua: 'здобувати', transcription: '[əˈtʃiːv]' },
    { en: 'avoid', ua: 'уникати', transcription: '[əˈvɔɪd]' },
    { en: 'celebrate', ua: 'святкувати', transcription: '[ˈseləbreɪt]' },
    { en: 'collect', ua: 'збирати', transcription: '[kəˈlekt]' },
    { en: 'compare', ua: 'порівнювати', transcription: '[kəmˈper]' },
    { en: 'connect', ua: "з'єднувати", transcription: '[kəˈnekt]' },
    { en: 'convince', ua: 'переконувати', transcription: '[kənˈvɪns]' },
    { en: 'count', ua: 'рахувати', transcription: '[kaʊnt]' },
  ],
  'verb',
);

// ─── Іменники ─────────────────────────────────────────────────────────────────

const NOUNS = tag(
  [
    { en: 'time', ua: 'час', transcription: '[taɪm]' },
    { en: 'person', ua: 'людина', transcription: '[ˈpɜːrsn]' },
    { en: 'year', ua: 'рік', transcription: '[jɪr]' },
    { en: 'way', ua: 'спосіб', transcription: '[weɪ]' },
    { en: 'day', ua: 'день', transcription: '[deɪ]' },
    { en: 'thing', ua: 'річ', transcription: '[θɪŋ]' },
    { en: 'man', ua: 'чоловік', transcription: '[mæn]' },
    { en: 'world', ua: 'світ', transcription: '[wɜːrld]' },
    { en: 'life', ua: 'життя', transcription: '[laɪf]' },
    { en: 'hand', ua: 'рука', transcription: '[hænd]' },
    { en: 'part', ua: 'частина', transcription: '[pɑːrt]' },
    { en: 'place', ua: 'місце', transcription: '[pleɪs]' },
    { en: 'week', ua: 'тиждень', transcription: '[wiːk]' },
    { en: 'company', ua: 'компанія', transcription: '[ˈkʌmpəni]' },
    { en: 'group', ua: 'група', transcription: '[ɡruːp]' },
    { en: 'problem', ua: 'проблема', transcription: '[ˈprɑːbləm]' },
    { en: 'fact', ua: 'факт', transcription: '[fækt]' },
    { en: 'money', ua: 'гроші', transcription: '[ˈmʌni]' },
    { en: 'number', ua: 'число', transcription: '[ˈnʌmbər]' },
    { en: 'night', ua: 'ніч', transcription: '[naɪt]' },
    { en: 'city', ua: 'місто', transcription: '[ˈsɪti]' },
    { en: 'name', ua: "ім'я", transcription: '[neɪm]' },
    { en: 'home', ua: 'дім', transcription: '[hoʊm]' },
    { en: 'water', ua: 'вода', transcription: '[ˈwɔːtər]' },
    { en: 'room', ua: 'кімната', transcription: '[ruːm]' },
    { en: 'mother', ua: 'мати', transcription: '[ˈmʌðər]' },
    { en: 'area', ua: 'ділянка', transcription: '[ˈeriə]' },
    { en: 'family', ua: "сім'я", transcription: '[ˈfæməli]' },
    { en: 'body', ua: 'тіло', transcription: '[ˈbɑːdi]' },
    { en: 'eye', ua: 'око', transcription: '[aɪ]' },
    { en: 'food', ua: 'їжа', transcription: '[fuːd]' },
    { en: 'child', ua: 'дитина', transcription: '[tʃaɪld]' },
    { en: 'door', ua: 'двері', transcription: '[dɔːr]' },
    { en: 'country', ua: 'країна', transcription: '[ˈkʌntri]' },
    { en: 'question', ua: 'питання', transcription: '[ˈkwestʃən]' },
    { en: 'head', ua: 'голова', transcription: '[hed]' },
    { en: 'heart', ua: 'серце', transcription: '[hɑːrt]' },
    { en: 'idea', ua: 'ідея', transcription: '[aɪˈdiːə]' },
    { en: 'school', ua: 'школа', transcription: '[skuːl]' },
    { en: 'story', ua: 'оповідання', transcription: '[ˈstɔːri]' },
    { en: 'book', ua: 'книга', transcription: '[bʊk]' },
    { en: 'street', ua: 'вулиця', transcription: '[striːt]' },
    { en: 'moment', ua: 'мить', transcription: '[ˈmoʊmənt]' },
    { en: 'face', ua: 'обличчя', transcription: '[feɪs]' },
    { en: 'friend', ua: 'друг', transcription: '[frend]' },
    { en: 'morning', ua: 'ранок', transcription: '[ˈmɔːrnɪŋ]' },
    { en: 'girl', ua: 'дівчина', transcription: '[ɡɜːrl]' },
    { en: 'boy', ua: 'хлопець', transcription: '[bɔɪ]' },
    { en: 'power', ua: 'сила', transcription: '[ˈpaʊər]' },
    { en: 'word', ua: 'слово', transcription: '[wɜːrd]' },
    { en: 'road', ua: 'дорога', transcription: '[roʊd]' },
    { en: 'month', ua: 'місяць', transcription: '[mʌnθ]' },
    { en: 'line', ua: 'лінія', transcription: '[laɪn]' },
    { en: 'government', ua: 'уряд', transcription: '[ˈɡʌvərnmənt]' },
    { en: 'car', ua: 'автомобіль', transcription: '[kɑːr]' },
    { en: 'town', ua: 'містечко', transcription: '[taʊn]' },
    { en: 'language', ua: 'мова', transcription: '[ˈlæŋɡwɪdʒ]' },
    { en: 'level', ua: 'рівень', transcription: '[ˈlevəl]' },
    { en: 'air', ua: 'повітря', transcription: '[er]' },
    { en: 'hour', ua: 'година', transcription: '[aʊər]' },
    { en: 'game', ua: 'гра', transcription: '[ɡeɪm]' },
    { en: 'fire', ua: 'вогонь', transcription: '[faɪər]' },
    { en: 'land', ua: 'земля', transcription: '[lænd]' },
    { en: 'age', ua: 'вік', transcription: '[eɪdʒ]' },
    { en: 'voice', ua: 'голос', transcription: '[vɔɪs]' },
    { en: 'color', ua: 'колір', transcription: '[ˈkʌlər]' },
    { en: 'sound', ua: 'звук', transcription: '[saʊnd]' },
    { en: 'news', ua: 'новини', transcription: '[njuːz]' },
    { en: 'light', ua: 'світло', transcription: '[laɪt]' },
    { en: 'type', ua: 'тип', transcription: '[taɪp]' },
    { en: 'class', ua: 'клас', transcription: '[klæs]' },
    { en: 'period', ua: 'період', transcription: '[ˈpɪriəd]' },
    { en: 'building', ua: 'будівля', transcription: '[ˈbɪldɪŋ]' },
    { en: 'field', ua: 'поле', transcription: '[fiːld]' },
    { en: 'business', ua: 'бізнес', transcription: '[ˈbɪznɪs]' },
    { en: 'picture', ua: 'картина', transcription: '[ˈpɪktʃər]' },
    { en: 'space', ua: 'простір', transcription: '[speɪs]' },
    { en: 'view', ua: 'вид', transcription: '[vjuː]' },
    { en: 'house', ua: 'будинок', transcription: '[haʊs]' },
    { en: 'team', ua: 'команда', transcription: '[tiːm]' },
    { en: 'service', ua: 'послуга', transcription: '[ˈsɜːrvɪs]' },
    { en: 'price', ua: 'ціна', transcription: '[praɪs]' },
    { en: 'hair', ua: 'волосся', transcription: '[her]' },
    { en: 'rest', ua: 'відпочинок', transcription: '[rest]' },
    { en: 'step', ua: 'крок', transcription: '[step]' },
    { en: 'law', ua: 'закон', transcription: '[lɔː]' },
    { en: 'century', ua: 'століття', transcription: '[ˈsentʃəri]' },
    { en: 'state', ua: 'держава', transcription: '[steɪt]' },
    { en: 'war', ua: 'війна', transcription: '[wɔːr]' },
    { en: 'party', ua: 'вечірка', transcription: '[ˈpɑːrti]' },
    { en: 'society', ua: 'суспільство', transcription: '[səˈsaɪəti]' },
    { en: 'music', ua: 'музика', transcription: '[ˈmjuːzɪk]' },
    { en: 'office', ua: 'офіс', transcription: '[ˈɔːfɪs]' },
    { en: 'position', ua: 'позиція', transcription: '[pəˈzɪʃən]' },
    { en: 'role', ua: 'роль', transcription: '[roʊl]' },
    { en: 'president', ua: 'президент', transcription: '[ˈprezɪdənt]' },
    { en: 'decision', ua: 'рішення', transcription: '[dɪˈsɪʒən]' },
    { en: 'reason', ua: 'причина', transcription: '[ˈriːzən]' },
    { en: 'nature', ua: 'природа', transcription: '[ˈneɪtʃər]' },
    { en: 'system', ua: 'система', transcription: '[ˈsɪstəm]' },
    { en: 'love', ua: 'кохання', transcription: '[lʌv]' },
    { en: 'plan', ua: 'план', transcription: '[plæn]' },
    { en: 'art', ua: 'мистецтво', transcription: '[ɑːrt]' },
    { en: 'development', ua: 'розвиток', transcription: '[dɪˈveləpmənt]' },
    { en: 'security', ua: 'безпека', transcription: '[sɪˈkjʊrɪti]' },
    { en: 'future', ua: 'майбутнє', transcription: '[ˈfjuːtʃər]' },
    { en: 'chance', ua: 'шанс', transcription: '[tʃæns]' },
    { en: 'change', ua: 'зміна', transcription: '[tʃeɪndʒ]' },
    { en: 'community', ua: 'спільнота', transcription: '[kəˈmjuːnɪti]' },
    { en: 'center', ua: 'центр', transcription: '[ˈsentər]' },
    { en: 'result', ua: 'результат', transcription: '[rɪˈzʌlt]' },
    { en: 'model', ua: 'модель', transcription: '[ˈmɑːdl]' },
    { en: 'economy', ua: 'економіка', transcription: '[ɪˈkɑːnəmi]' },
    { en: 'energy', ua: 'енергія', transcription: '[ˈenərdʒi]' },
    { en: 'experience', ua: 'досвід', transcription: '[ɪkˈspɪriəns]' },
    { en: 'education', ua: 'освіта', transcription: '[ˌedʒuˈkeɪʃən]' },
    { en: 'success', ua: 'успіх', transcription: '[səkˈses]' },
    { en: 'value', ua: 'цінність', transcription: '[ˈvæljuː]' },
    { en: 'history', ua: 'історія', transcription: '[ˈhɪstri]' },
    { en: 'paper', ua: 'папір', transcription: '[ˈpeɪpər]' },
    { en: 'research', ua: 'дослідження', transcription: '[rɪˈsɜːrtʃ]' },
    { en: 'ability', ua: 'здібність', transcription: '[əˈbɪlɪti]' },
    { en: 'relationship', ua: 'стосунки', transcription: '[rɪˈleɪʃənʃɪp]' },
    { en: 'evening', ua: 'вечір', transcription: '[ˈiːvnɪŋ]' },
    { en: 'attention', ua: 'увага', transcription: '[əˈtenʃən]' },
    { en: 'culture', ua: 'культура', transcription: '[ˈkʌltʃər]' },
    { en: 'truth', ua: 'правда', transcription: '[truːθ]' },
    { en: 'leader', ua: 'лідер', transcription: '[ˈliːdər]' },
    { en: 'student', ua: 'студент', transcription: '[ˈstuːdnt]' },
    { en: 'teacher', ua: 'вчитель', transcription: '[ˈtiːtʃər]' },
    { en: 'parent', ua: 'батьки', transcription: '[ˈperənt]' },
    { en: 'window', ua: 'вікно', transcription: '[ˈwɪndoʊ]' },
    { en: 'table', ua: 'стіл', transcription: '[ˈteɪbəl]' },
    { en: 'chair', ua: 'стілець', transcription: '[tʃer]' },
    { en: 'bed', ua: 'ліжко', transcription: '[bed]' },
    { en: 'sun', ua: 'сонце', transcription: '[sʌn]' },
    { en: 'tree', ua: 'дерево', transcription: '[triː]' },
    { en: 'river', ua: 'річка', transcription: '[ˈrɪvər]' },
    { en: 'sea', ua: 'море', transcription: '[siː]' },
    { en: 'mountain', ua: 'гора', transcription: '[ˈmaʊntən]' },
    { en: 'sky', ua: 'небо', transcription: '[skaɪ]' },
    { en: 'animal', ua: 'тварина', transcription: '[ˈænɪməl]' },
    { en: 'dog', ua: 'собака', transcription: '[dɔːɡ]' },
    { en: 'cat', ua: 'кіт', transcription: '[kæt]' },
    { en: 'bird', ua: 'птах', transcription: '[bɜːrd]' },
    { en: 'fish', ua: 'риба', transcription: '[fɪʃ]' },
    { en: 'flower', ua: 'квітка', transcription: '[ˈflaʊər]' },
    { en: 'garden', ua: 'сад', transcription: '[ˈɡɑːrdən]' },
    { en: 'store', ua: 'магазин', transcription: '[stɔːr]' },
    { en: 'hospital', ua: 'лікарня', transcription: '[ˈhɑːspɪtl]' },
    { en: 'letter', ua: 'лист', transcription: '[ˈletər]' },
    { en: 'doctor', ua: 'лікар', transcription: '[ˈdɑːktər]' },
    { en: 'police', ua: 'поліція', transcription: '[pəˈliːs]' },
    { en: 'soldier', ua: 'солдат', transcription: '[ˈsoʊldʒər]' },
    { en: 'king', ua: 'король', transcription: '[kɪŋ]' },
    { en: 'queen', ua: 'королева', transcription: '[kwiːn]' },
    { en: 'baby', ua: 'немовля', transcription: '[ˈbeɪbi]' },
    { en: 'brother', ua: 'брат', transcription: '[ˈbrʌðər]' },
    { en: 'sister', ua: 'сестра', transcription: '[ˈsɪstər]' },
    { en: 'father', ua: 'батько', transcription: '[ˈfɑːðər]' },
    { en: 'wife', ua: 'дружина', transcription: '[waɪf]' },
    { en: 'son', ua: 'син', transcription: '[sʌn]' },
    { en: 'daughter', ua: 'дочка', transcription: '[ˈdɔːtər]' },
    { en: 'neighbor', ua: 'сусід', transcription: '[ˈneɪbər]' },
    { en: 'enemy', ua: 'ворог', transcription: '[ˈenəmi]' },
    { en: 'church', ua: 'церква', transcription: '[tʃɜːrtʃ]' },
    { en: 'library', ua: 'бібліотека', transcription: '[ˈlaɪbreri]' },
    { en: 'airport', ua: 'аеропорт', transcription: '[ˈerpɔːrt]' },
    { en: 'station', ua: 'станція', transcription: '[ˈsteɪʃən]' },
    { en: 'army', ua: 'армія', transcription: '[ˈɑːrmi]' },
    { en: 'forest', ua: 'ліс', transcription: '[ˈfɔːrɪst]' },
    { en: 'lake', ua: 'озеро', transcription: '[leɪk]' },
    { en: 'beach', ua: 'пляж', transcription: '[biːtʃ]' },
    { en: 'rain', ua: 'дощ', transcription: '[reɪn]' },
    { en: 'snow', ua: 'сніг', transcription: '[snoʊ]' },
    { en: 'star', ua: 'зірка', transcription: '[stɑːr]' },
  ],
  'noun',
);

// ─── Прикметники ──────────────────────────────────────────────────────────────

const ADJECTIVES = tag(
  [
    { en: 'good', ua: 'добрий', transcription: '[ɡʊd]' },
    { en: 'new', ua: 'новий', transcription: '[njuː]' },
    { en: 'first', ua: 'перший', transcription: '[fɜːrst]' },
    { en: 'last', ua: 'останній', transcription: '[læst]' },
    { en: 'long', ua: 'довгий', transcription: '[lɔːŋ]' },
    { en: 'great', ua: 'чудовий', transcription: '[ɡreɪt]' },
    { en: 'little', ua: 'маленький', transcription: '[ˈlɪtl]' },
    { en: 'own', ua: 'власний', transcription: '[oʊn]' },
    { en: 'other', ua: 'інший', transcription: '[ˈʌðər]' },
    { en: 'old', ua: 'старий', transcription: '[oʊld]' },
    { en: 'right', ua: 'правильний', transcription: '[raɪt]' },
    { en: 'big', ua: 'великий', transcription: '[bɪɡ]' },
    { en: 'high', ua: 'високий', transcription: '[haɪ]' },
    { en: 'different', ua: 'різний', transcription: '[ˈdɪfrənt]' },
    { en: 'small', ua: 'малий', transcription: '[smɔːl]' },
    { en: 'large', ua: 'великий', transcription: '[lɑːrdʒ]' },
    { en: 'next', ua: 'наступний', transcription: '[nekst]' },
    { en: 'early', ua: 'ранній', transcription: '[ˈɜːrli]' },
    { en: 'young', ua: 'молодий', transcription: '[jʌŋ]' },
    { en: 'important', ua: 'важливий', transcription: '[ɪmˈpɔːrtənt]' },
    { en: 'public', ua: 'публічний', transcription: '[ˈpʌblɪk]' },
    { en: 'bad', ua: 'поганий', transcription: '[bæd]' },
    { en: 'same', ua: 'однаковий', transcription: '[seɪm]' },
    { en: 'able', ua: 'здатний', transcription: '[ˈeɪbəl]' },
    { en: 'real', ua: 'справжній', transcription: '[riːl]' },
    { en: 'best', ua: 'найкращий', transcription: '[best]' },
    { en: 'free', ua: 'вільний', transcription: '[friː]' },
    { en: 'sure', ua: 'впевнений', transcription: '[ʃʊr]' },
    { en: 'better', ua: 'кращий', transcription: '[ˈbetər]' },
    { en: 'true', ua: 'правдивий', transcription: '[truː]' },
    { en: 'hard', ua: 'складний', transcription: '[hɑːrd]' },
    { en: 'low', ua: 'низький', transcription: '[loʊ]' },
    { en: 'short', ua: 'короткий', transcription: '[ʃɔːrt]' },
    { en: 'clear', ua: 'чіткий', transcription: '[klɪr]' },
    { en: 'recent', ua: 'нещодавній', transcription: '[ˈriːsnt]' },
    { en: 'left', ua: 'лівий', transcription: '[left]' },
    { en: 'political', ua: 'політичний', transcription: '[pəˈlɪtɪkl]' },
    { en: 'social', ua: 'соціальний', transcription: '[ˈsoʊʃl]' },
    { en: 'economic', ua: 'економічний', transcription: '[ˌiːkəˈnɑːmɪk]' },
    { en: 'local', ua: 'місцевий', transcription: '[ˈloʊkl]' },
    { en: 'national', ua: 'національний', transcription: '[ˈnæʃənl]' },
    { en: 'full', ua: 'повний', transcription: '[fʊl]' },
    { en: 'hot', ua: 'гарячий', transcription: '[hɑːt]' },
    { en: 'dark', ua: 'темний', transcription: '[dɑːrk]' },
    { en: 'strong', ua: 'сильний', transcription: '[strɔːŋ]' },
    { en: 'deep', ua: 'глибокий', transcription: '[diːp]' },
    { en: 'heavy', ua: 'важкий', transcription: '[ˈhevi]' },
    { en: 'cold', ua: 'холодний', transcription: '[koʊld]' },
    { en: 'warm', ua: 'теплий', transcription: '[wɔːrm]' },
    { en: 'clean', ua: 'чистий', transcription: '[kliːn]' },
    { en: 'dry', ua: 'сухий', transcription: '[draɪ]' },
    { en: 'wrong', ua: 'неправильний', transcription: '[rɔːŋ]' },
    { en: 'happy', ua: 'щасливий', transcription: '[ˈhæpi]' },
    { en: 'late', ua: 'пізній', transcription: '[leɪt]' },
    { en: 'ready', ua: 'готовий', transcription: '[ˈredi]' },
    { en: 'simple', ua: 'простий', transcription: '[ˈsɪmpl]' },
    { en: 'possible', ua: 'можливий', transcription: '[ˈpɑːsəbl]' },
    { en: 'whole', ua: 'цілий', transcription: '[hoʊl]' },
    { en: 'past', ua: 'минулий', transcription: '[pæst]' },
    { en: 'white', ua: 'білий', transcription: '[waɪt]' },
    { en: 'black', ua: 'чорний', transcription: '[blæk]' },
    { en: 'special', ua: 'особливий', transcription: '[ˈspeʃl]' },
    { en: 'easy', ua: 'легкий', transcription: '[ˈiːzi]' },
    { en: 'personal', ua: 'особистий', transcription: '[ˈpɜːrsənl]' },
    { en: 'poor', ua: 'бідний', transcription: '[pʊr]' },
    { en: 'rich', ua: 'багатий', transcription: '[rɪtʃ]' },
    { en: 'similar', ua: 'схожий', transcription: '[ˈsɪmɪlər]' },
    { en: 'main', ua: 'головний', transcription: '[meɪn]' },
    { en: 'necessary', ua: 'необхідний', transcription: '[ˈnesəseri]' },
    { en: 'positive', ua: 'позитивний', transcription: '[ˈpɑːzɪtɪv]' },
    { en: 'safe', ua: 'безпечний', transcription: '[seɪf]' },
    { en: 'wide', ua: 'широкий', transcription: '[waɪd]' },
    { en: 'far', ua: 'далекий', transcription: '[fɑːr]' },
    { en: 'fast', ua: 'швидкий', transcription: '[fæst]' },
    { en: 'certain', ua: 'певний', transcription: '[ˈsɜːrtn]' },
    { en: 'near', ua: 'близький', transcription: '[nɪr]' },
    { en: 'difficult', ua: 'важкий', transcription: '[ˈdɪfɪkəlt]' },
    { en: 'serious', ua: 'серйозний', transcription: '[ˈsɪriəs]' },
    { en: 'likely', ua: 'імовірний', transcription: '[ˈlaɪkli]' },
    { en: 'central', ua: 'центральний', transcription: '[ˈsentrəl]' },
    { en: 'final', ua: 'кінцевий', transcription: '[ˈfaɪnl]' },
    { en: 'human', ua: 'людський', transcription: '[ˈhjuːmən]' },
    { en: 'general', ua: 'загальний', transcription: '[ˈdʒenərəl]' },
    { en: 'common', ua: 'звичайний', transcription: '[ˈkɑːmən]' },
    { en: 'direct', ua: 'прямий', transcription: '[dɪˈrekt]' },
    { en: 'beautiful', ua: 'красивий', transcription: '[ˈbjuːtɪfl]' },
    { en: 'red', ua: 'червоний', transcription: '[red]' },
    { en: 'blue', ua: 'синій', transcription: '[bluː]' },
    { en: 'green', ua: 'зелений', transcription: '[ɡriːn]' },
    { en: 'yellow', ua: 'жовтий', transcription: '[ˈjeloʊ]' },
    { en: 'purple', ua: 'фіолетовий', transcription: '[ˈpɜːrpl]' },
    { en: 'orange', ua: 'помаранчевий', transcription: '[ˈɔːrɪndʒ]' },
    { en: 'grey', ua: 'сірий', transcription: '[ɡreɪ]' },
    { en: 'brown', ua: 'коричневий', transcription: '[braʊn]' },
    { en: 'alive', ua: 'живий', transcription: '[əˈlaɪv]' },
    { en: 'dead', ua: 'мертвий', transcription: '[ded]' },
    { en: 'angry', ua: 'злий', transcription: '[ˈæŋɡri]' },
    { en: 'afraid', ua: 'наляканий', transcription: '[əˈfreɪd]' },
    { en: 'alone', ua: 'самотній', transcription: '[əˈloʊn]' },
    { en: 'amazing', ua: 'дивовижний', transcription: '[əˈmeɪzɪŋ]' },
    { en: 'ancient', ua: 'стародавній', transcription: '[ˈeɪnʃənt]' },
    { en: 'bright', ua: 'яскравий', transcription: '[braɪt]' },
    { en: 'busy', ua: 'зайнятий', transcription: '[ˈbɪzi]' },
    { en: 'careful', ua: 'обережний', transcription: '[ˈkerfəl]' },
    { en: 'cheap', ua: 'дешевий', transcription: '[tʃiːp]' },
    { en: 'expensive', ua: 'дорогий', transcription: '[ɪkˈspensɪv]' },
    { en: 'famous', ua: 'відомий', transcription: '[ˈfeɪməs]' },
    { en: 'foreign', ua: 'іноземний', transcription: '[ˈfɔːrən]' },
    { en: 'healthy', ua: 'здоровий', transcription: '[ˈhelθi]' },
    { en: 'honest', ua: 'чесний', transcription: '[ˈɑːnɪst]' },
    { en: 'hungry', ua: 'голодний', transcription: '[ˈhʌŋɡri]' },
    { en: 'kind', ua: 'лагідний', transcription: '[kaɪnd]' },
    { en: 'lazy', ua: 'ледачий', transcription: '[ˈleɪzi]' },
    { en: 'lucky', ua: 'везучий', transcription: '[ˈlʌki]' },
    { en: 'noisy', ua: 'шумний', transcription: '[ˈnɔɪzi]' },
    { en: 'quiet', ua: 'тихий', transcription: '[ˈkwaɪət]' },
    { en: 'sharp', ua: 'гострий', transcription: '[ʃɑːrp]' },
    { en: 'sick', ua: 'хворий', transcription: '[sɪk]' },
    { en: 'soft', ua: "м'який", transcription: '[sɔːft]' },
    { en: 'sweet', ua: 'солодкий', transcription: '[swiːt]' },
    { en: 'terrible', ua: 'жахливий', transcription: '[ˈterɪbl]' },
    { en: 'thin', ua: 'тонкий', transcription: '[θɪn]' },
    { en: 'ugly', ua: 'потворний', transcription: '[ˈʌɡli]' },
    { en: 'useful', ua: 'корисний', transcription: '[ˈjuːsfəl]' },
    { en: 'weak', ua: 'слабкий', transcription: '[wiːk]' },
    { en: 'wise', ua: 'мудрий', transcription: '[waɪz]' },
  ],
  'adjective',
);

// ─── Прислівники ──────────────────────────────────────────────────────────────

const ADVERBS = tag(
  [
    { en: 'very', ua: 'дуже', transcription: '[ˈveri]' },
    { en: 'also', ua: 'також', transcription: '[ˈɔːlsoʊ]' },
    { en: 'just', ua: 'просто', transcription: '[dʒʌst]' },
    { en: 'only', ua: 'тільки', transcription: '[ˈoʊnli]' },
    { en: 'still', ua: 'ще', transcription: '[stɪl]' },
    { en: 'never', ua: 'ніколи', transcription: '[ˈnevər]' },
    { en: 'always', ua: 'завжди', transcription: '[ˈɔːlweɪz]' },
    { en: 'often', ua: 'часто', transcription: '[ˈɔːfən]' },
    { en: 'together', ua: 'разом', transcription: '[təˈɡeðər]' },
    { en: 'already', ua: 'вже', transcription: '[ɔːlˈredi]' },
    { en: 'again', ua: 'знову', transcription: '[əˈɡen]' },
    { en: 'almost', ua: 'майже', transcription: '[ˈɔːlmoʊst]' },
    { en: 'above', ua: 'над', transcription: '[əˈbʌv]' },
    { en: 'around', ua: 'навколо', transcription: '[əˈraʊnd]' },
    { en: 'once', ua: 'один раз', transcription: '[wʌns]' },
    { en: 'too', ua: 'теж', transcription: '[tuː]' },
    { en: 'away', ua: 'геть', transcription: '[əˈweɪ]' },
    { en: 'ago', ua: 'тому', transcription: '[əˈɡoʊ]' },
    { en: 'yet', ua: 'ще', transcription: '[jet]' },
    { en: 'perhaps', ua: 'можливо', transcription: '[pərˈhæps]' },
    { en: 'suddenly', ua: 'раптово', transcription: '[ˈsʌdənli]' },
    { en: 'especially', ua: 'особливо', transcription: '[ɪˈspeʃəli]' },
    { en: 'exactly', ua: 'точно', transcription: '[ɪɡˈzæktli]' },
    { en: 'rather', ua: 'досить', transcription: '[ˈræðər]' },
    { en: 'soon', ua: 'незабаром', transcription: '[suːn]' },
    { en: 'recently', ua: 'нещодавно', transcription: '[ˈriːsntli]' },
    { en: 'probably', ua: 'мабуть', transcription: '[ˈprɑːbəbli]' },
    { en: 'usually', ua: 'зазвичай', transcription: '[ˈjuːʒuəli]' },
    { en: 'quickly', ua: 'швидко', transcription: '[ˈkwɪkli]' },
    { en: 'slowly', ua: 'повільно', transcription: '[ˈsloʊli]' },
    { en: 'finally', ua: 'нарешті', transcription: '[ˈfaɪnəli]' },
    { en: 'really', ua: 'справді', transcription: '[ˈriːəli]' },
    { en: 'actually', ua: 'насправді', transcription: '[ˈæktʃuəli]' },
    { en: 'certainly', ua: 'звичайно', transcription: '[ˈsɜːrtnli]' },
    { en: 'completely', ua: 'повністю', transcription: '[kəmˈpliːtli]' },
    { en: 'directly', ua: 'безпосередньо', transcription: '[dɪˈrektli]' },
    { en: 'easily', ua: 'легко', transcription: '[ˈiːzɪli]' },
    { en: 'generally', ua: 'загалом', transcription: '[ˈdʒenərəli]' },
    { en: 'immediately', ua: 'негайно', transcription: '[ɪˈmiːdiətli]' },
    { en: 'simply', ua: 'просто', transcription: '[ˈsɪmpli]' },
    { en: 'clearly', ua: 'чітко', transcription: '[ˈklɪrli]' },
    { en: 'carefully', ua: 'обережно', transcription: '[ˈkerfəli]' },
    { en: 'deeply', ua: 'глибоко', transcription: '[ˈdiːpli]' },
    { en: 'loudly', ua: 'гучно', transcription: '[ˈlaʊdli]' },
    { en: 'strongly', ua: 'сильно', transcription: '[ˈstrɔːŋli]' },
    { en: 'highly', ua: 'надзвичайно', transcription: '[ˈhaɪli]' },
    { en: 'widely', ua: 'широко', transcription: '[ˈwaɪdli]' },
    { en: 'nearly', ua: 'майже', transcription: '[ˈnɪrli]' },
  ],
  'adverb',
);

// ─── Exports ──────────────────────────────────────────────────────────────────

export const WORDS: Word[] = [...VERBS, ...NOUNS, ...ADJECTIVES, ...ADVERBS];

export const WORDS_BY_CATEGORY: Record<WordCategory, Word[]> = {
  verb: VERBS,
  noun: NOUNS,
  adjective: ADJECTIVES,
  adverb: ADVERBS,
};
